const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
let adStorm=true;
const adTitles=['CONGRATULATIONS!!!','IMPORTANT SYSTEM NOTICE','FREE CURSOR PACK','HOT LOCAL TOOLBARS','YOU WON A PIXEL','DOWNLOAD NOW','WARNING: VIBES DETECTED','1999 CALLED'];
const adBodies=[
  'You are the 1,000,000th visitor! Your prize is one emotionally confusing button.',
  'Your browser needs more neon. Install 87 themes now?',
  'FREE dancing skeleton cursors. Not real. Still tempting.',
  'A mysterious goblin has detected unused RAM. Please panic calmly.',
  'Your hard drive contains 14 mystery bolts and one file named final_final_REAL2.',
  'Claim your complimentary virtual pizza roll before it gets cold.',
  'Your screen has achieved maximum retro density. Add more? Obviously.',
  'This ad is fake and harmless, but spiritually annoying.'
];
function visitorCounter(){const n=(Number(localStorage.retroVisitors||1998)+1);localStorage.retroVisitors=n; const el=$('#counter'); if(el) el.textContent=String(n).padStart(8,'0')}
function randomQuote(){const q=['A suspiciously powerful Honda Fit approaches.','This website contains 37% more goblin energy than legally advised.','WARNING: The hamster powering this page has escaped.','You found the secret smell of warm CRT plastic.','Inline-3 at 9k RPM? spiritually yes.','This page is best viewed in a thunderstorm.','Do not feed the cursor after midnight.','A pop-up ad is watching from the corner.','The fake video logo is training for the corner hit.']; const el=$('#quote'); if(el) el.textContent=q[Math.floor(Math.random()*q.length)]}
function spawnConfetti(){for(let i=0;i<25;i++){let d=document.createElement('div');d.textContent=['★','◆','✦','☻','※','░','▓','▒'][Math.floor(Math.random()*8)];Object.assign(d.style,{position:'fixed',left:Math.random()*100+'vw',top:'-20px',fontSize:12+Math.random()*28+'px',color:`hsl(${Math.random()*360},100%,70%)`,zIndex:998,pointerEvents:'none'});document.body.appendChild(d);let y=0,rot=0;let id=setInterval(()=>{y+=3+Math.random()*4;rot+=12;d.style.transform=`translateY(${y}px) rotate(${rot}deg)`;if(y>innerHeight+60){clearInterval(id);d.remove()}},30)}}
function spawnSticker(){let d=document.createElement('div');d.className='sticker';d.textContent=['🧊','💿','🛸','🦝','📼','⚠️','🔧','🕹️','🧃','🐟'][Math.floor(Math.random()*10)];d.style.left=Math.random()*90+'vw';d.style.top=Math.random()*85+'vh';document.body.appendChild(d);setTimeout(()=>d.remove(),2700)}
function spawnAd(manual=false){
  const maxAds=manual?99:7; if(document.querySelectorAll('.popup-ad').length>=maxAds)return;
  const ad=document.createElement('div');ad.className='popup-ad';
  ad.style.left=Math.max(5,Math.random()*(innerWidth-330))+'px';ad.style.top=Math.max(5,Math.random()*(innerHeight-230))+'px';
  const title=adTitles[Math.floor(Math.random()*adTitles.length)], body=adBodies[Math.floor(Math.random()*adBodies.length)];
  ad.innerHTML=`<div class='ad-title'><span>${title}</span><button class='x' title='close'>X</button></div><div class='ad-body'><b>${body}</b><p>${['Click here for nothing!','Your PC is already retro enough.','Limited time fake offer!','This could have been a normal website.'][Math.floor(Math.random()*4)]}</p><div class='fake-progress'></div><p><button>OK</button><button>later</button><button>why</button></p><p class='ad-fine'>This is a fake pop-up. It does not install anything. It merely has bad manners.</p></div>`;
  document.body.appendChild(ad); ad.querySelector('.x').onclick=()=>ad.remove(); ad.querySelectorAll('.ad-body button').forEach(b=>b.onclick=()=>{spawnSticker(); if(Math.random()>.55) spawnAd(true)});
  makeDraggable(ad, ad.querySelector('.ad-title'));
  if(!manual)setTimeout(()=>{if(ad.isConnected && Math.random()>.25)ad.remove()},9000+Math.random()*8000)
}
function toggleAdStorm(){adStorm=!adStorm; alert('Fake ad storm '+(adStorm?'enabled':'paused'))}
function scheduleAds(){setTimeout(()=>{if(adStorm)spawnAd(false);scheduleAds()},2500+Math.random()*6500)}
function makeDraggable(el,handle){let ox=0,oy=0,down=false;handle.onmousedown=e=>{down=true;ox=e.clientX-el.offsetLeft;oy=e.clientY-el.offsetTop;e.preventDefault()};addEventListener('mousemove',e=>{if(!down)return;el.style.left=(e.clientX-ox)+'px';el.style.top=(e.clientY-oy)+'px'});addEventListener('mouseup',()=>down=false)}
function bouncingLogo(){
  if($('.bounce-logo'))return; const logo=document.createElement('div');logo.className='bounce-logo';logo.innerHTML='<div>VDO<small>RETRO VIDEO</small></div>';document.body.appendChild(logo);
  let x=40+Math.random()*120,y=60+Math.random()*120,vx=2.2,vy=1.8,hue=0;
  function step(){const w=logo.offsetWidth,h=logo.offsetHeight; x+=vx;y+=vy; let hit=false; if(x<0||x+w>innerWidth){vx*=-1;x=Math.max(0,Math.min(x,innerWidth-w));hit=true} if(y<0||y+h>innerHeight){vy*=-1;y=Math.max(0,Math.min(y,innerHeight-h));hit=true} if(hit){hue=(hue+75)%360;logo.style.filter=`hue-rotate(${hue}deg)`; if(Math.random()>.82)spawnSticker()} logo.style.transform=`translate(${x}px,${y}px)`; requestAnimationFrame(step)} step();
}
function clickGame(){const area=$('#clickGame'); if(!area)return; let score=0; const scoreEl=$('#score'); function make(){const t=document.createElement('div');t.className='target';t.textContent=['🛸','👾','💿','🧃','🦴','🚗','🧊','📼','🧌'][Math.floor(Math.random()*9)];t.style.left=Math.random()*85+'%';t.style.top=Math.random()*75+'%';t.onclick=()=>{score++;scoreEl.textContent=score;t.remove();make(); if(score%5===0)spawnAd(false)};area.appendChild(t)} make();}
function bugGame(){const area=$('#bugGame'); if(!area)return; let score=0; const out=$('#bugScore'); function bug(){const b=document.createElement('div');b.className='bug';b.textContent=['🪲','🐛','🪳','🦟'][Math.floor(Math.random()*4)];b.style.left=Math.random()*90+'%';b.style.top=Math.random()*80+'%';b.onclick=()=>{score++;out.textContent=score;b.remove();spawnSticker()};area.appendChild(b);setTimeout(()=>{if(b.isConnected)b.remove()},2600)} setInterval(bug,650);}
let reactionReady=false,reactionStart=0,reactionTimer=0;function startReaction(){const box=$('#reactionBox'),out=$('#reactionOut'); if(!box)return; reactionReady=false; box.className='reaction-box'; box.textContent='wait for it...'; out.textContent=''; clearTimeout(reactionTimer); reactionTimer=setTimeout(()=>{reactionReady=true;reactionStart=performance.now();box.className='reaction-box go';box.textContent='GO! CLICK!'},900+Math.random()*2500); box.onclick=()=>{if(!reactionReady){box.className='reaction-box too-soon';box.textContent='TOO SOON';out.textContent='The goblin is disappointed.';clearTimeout(reactionTimer)}else{const ms=Math.round(performance.now()-reactionStart);out.textContent=`${ms} ms. ${ms<250?'actually cracked':'respectable goblin reflexes'}`;box.className='reaction-box';box.textContent='done';reactionReady=false}}}
function badPassword(){const parts=['goblin','turbo','icecube','crt','mysterybolt','pizza','toolbox','wire','raccoon','VDO'];$('#passOut').textContent=Array.from({length:4},()=>parts[Math.floor(Math.random()*parts.length)]).join('-')+'-'+Math.floor(Math.random()*9999)}
function fortune(){const f=['Your next snack will be elite.','A forgotten cable will become useful soon.','Beware the suspicious USB drive.','You will open 19 tabs and use 2 of them.','A tiny project will become a 3-month hyperfixation.','The car part you need is somehow behind another car part.','A pop-up will appear when morale is lowest.']; const out=$('#fortuneOut'); if(out) out.textContent=f[Math.floor(Math.random()*f.length)]}
function guestbook(){const form=$('#guestForm'),list=$('#guestList'); if(!form)return; const saved=JSON.parse(localStorage.guestbook||'[]'); const clean=s=>String(s).replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])); const render=()=>list.innerHTML=saved.map(x=>`<div class='box'><b>${clean(x.name)}</b> wrote:<br>${clean(x.msg)}</div>`).join('')||'<i>No one has signed. tragic.</i>'; form.onsubmit=e=>{e.preventDefault();saved.unshift({name:$('#gname').value||'Anonymous Goblin',msg:$('#gmsg').value||'I was here.'});localStorage.guestbook=JSON.stringify(saved.slice(0,20));render();form.reset()}; render();}
function fakeDownload(name){const out=$('#downloadOut'); if(out) out.innerHTML=`<b>${name}</b> failed successfully. A fake progress bar became emotionally attached.`; spawnAd(true)}
function randomThing(){const a=['haunted','turbocharged','glowing','discount','ancient','forbidden','soggy','overclocked']; const b=['keyboard','raccoon','ice cube','Suburban','CRT','floppy disk','pizza roll','garden hose','router']; $('#thingOut').textContent='You found: '+a[Math.floor(Math.random()*a.length)]+' '+b[Math.floor(Math.random()*b.length)]}
function boltOracle(){const msg=['That bolt was extra. Probably.','Do not start the engine yet.','It goes somewhere important, but not emotionally.','Put it in the cupholder and pretend this is normal.','Congratulations, you have invented weight reduction.'];$('#boltOut').textContent=msg[Math.floor(Math.random()*msg.length)]}
function projectIdea(){const ideas=['Build a traffic cone PC with a tiny status LCD.','Make a Unity room where every door leads to a weirder door.','Create a fake OS that only runs useless widgets.','Put a tiny aquarium page inside a fake desktop window.','Make a car maintenance tracker that insults you politely.','Make a web shrine to mystery cables.'];$('#ideaOut').textContent=ideas[Math.floor(Math.random()*ideas.length)]}
function goblinName(){const first=['Crumb','Moldy','Turbo','Beep','Socket','Dusty','Vapor','Clicky'];const last=['McToolbar','Wirechewer','Disksniffer','Popupper','Boltfinder','Cachegremlin','Pixelstomper'];$('#goblinOut').textContent=first[Math.floor(Math.random()*first.length)]+' '+last[Math.floor(Math.random()*last.length)]}
function lightPanel(){const p=$('#lightPanel'); if(!p)return; for(let i=0;i<24;i++){const l=document.createElement('div');l.className='light';l.onclick=()=>l.classList.toggle('on');p.appendChild(l)}}
function openFakeWindow(title,body){const w=document.createElement('div');w.className='fake-window';w.style.left=Math.max(10,Math.random()*(innerWidth-380))+'px';w.style.top=Math.max(10,Math.random()*(innerHeight-230))+'px';w.innerHTML=`<div class='win-title'><span>${title}</span><button class='x'>X</button></div><div class='win-body'><p>${body}</p><button>OK</button></div>`;document.body.appendChild(w);w.querySelector('.x').onclick=()=>w.remove();w.querySelector('.win-body button').onclick=()=>w.remove();makeDraggable(w,w.querySelector('.win-title'))}
function desktopClock(){const el=$('#clockBox'); if(!el)return; const tick=()=>el.textContent=new Date().toLocaleTimeString(); tick(); setInterval(tick,1000)}
function addFish(){const tank=$('#aquarium'); if(!tank)return; const f=document.createElement('div');f.className='fish';f.textContent=['🐟','🐠','🦀','🐡','🪼','👢'][Math.floor(Math.random()*6)];f.style.top=20+Math.random()*220+'px';f.style.animationDuration=7+Math.random()*12+'s';f.style.animationDelay=-(Math.random()*6)+'s';tank.appendChild(f)}
function feedFish(){const out=$('#fishOut'); if(out)out.textContent='The fish appreciate the suspicious browser crumbs.'; for(let i=0;i<4;i++)addFish()}
function aquarium(){if(!$('#aquarium'))return; for(let i=0;i<8;i++)addFish()}
function randomSecret(){return ['The corner hit will happen when you stop watching.','The guestbook knows what you typed in 2004.','Somewhere, a forgotten toolbar still updates.','A mystery cable becomes useful once every seven years.','The fake ad is afraid of the close button.'][Math.floor(Math.random()*5)]}
function makeNoiseText(btn){btn.textContent=['BEEP','BOOP','BZZT','YEAH','NOPE'][Math.floor(Math.random()*5)];spawnSticker()}
addEventListener('DOMContentLoaded',()=>{visitorCounter();randomQuote();clickGame();bugGame();guestbook();lightPanel();desktopClock();aquarium();bouncingLogo();scheduleAds();window.spawnConfetti=spawnConfetti;window.fortune=fortune;window.spawnAd=spawnAd;window.toggleAdStorm=toggleAdStorm;window.spawnSticker=spawnSticker;window.fakeDownload=fakeDownload;window.randomThing=randomThing;window.boltOracle=boltOracle;window.projectIdea=projectIdea;window.goblinName=goblinName;window.openFakeWindow=openFakeWindow;window.startReaction=startReaction;window.badPassword=badPassword;window.addFish=addFish;window.feedFish=feedFish;window.randomSecret=randomSecret;window.makeNoiseText=makeNoiseText;});
