const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => document.querySelectorAll(selector);

let adStorm = false;
let adStormTimer = 0;
let randomAdTimer = 0;
let reactionReady = false;
let reactionStart = 0;
let reactionTimer = 0;
let fortuneClicks = 0;
let fakeWindowTop = 4500;
let fakeWindowCount = 0;
let secretRitualCount = 0;
const MAX_POPUPS = 12;
let soundEnabled = localStorage.getItem("oddSoundEnabled") !== "false";
let audioContext = null;

const stickerBits = ["*", "#", "@", "%", "!!", "??", "VHS", "404", "CRT", "ZAP"];
const puffBits = ["*", "+", "x", "404", "CRT", "VHS", "ZAP", "!", "?", "pixel", "beep"];

const adTemplates = [
  {
    className:"ad-prize",
    title:"FAKE PRIZE WINDOW",
    icon:"$",
    body:"A pretend prize committee selected this archive tab for maximum blinking potential.",
    buttons:["admire prize","decline loudly","more glitter"],
    fine:"Parody popup. No prize, no purchase, no download."
  },
  {
    className:"ad-toolbar",
    title:"TOOLBAR SIMULATOR",
    icon:"===",
    body:"Add an imaginary toolbar with buttons for Weather, Wormhole, and Sandwich Status.",
    buttons:["preview toolbar","keep browser clean","why is it gray"],
    fine:"Nothing is installed. The toolbar is theatrical."
  },
  {
    className:"ad-fortune",
    title:"HOROSCOPE MODEM",
    icon:"*",
    body:"The stars say a mysterious link will open exactly when curiosity wins.",
    buttons:["read omen","shuffle fate","close portal"],
    fine:"For entertainment only. The modem has no license."
  },
  {
    className:"ad-banner",
    title:"DANCING BANNER AD",
    icon:"<>",
    body:"This banner has been dancing since 2002 and refuses to hydrate.",
    buttons:["dance back","clap twice","no rhythm"],
    fine:"Movement implied. Actual dance quality not guaranteed."
  },
  {
    className:"ad-download",
    title:"FAKE DOWNLOAD MANAGER",
    icon:"DL",
    body:"Preparing absolutely nothing.zip. Estimated time remaining: emotionally variable.",
    buttons:["pretend save","pause nothing","view progress"],
    fine:"No files are downloaded. The progress bar is decorative."
  },
  {
    className:"ad-visitor",
    title:"VISITOR NUMBER CLAIM",
    icon:"#",
    body:"You are visitor #" + String(Math.floor(1000 + Math.random() * 8999)) + " in a completely local hallucination.",
    buttons:["accept number","reroll number","frame it"],
    fine:"Visitor numbers are fake unless shown in the local counter box."
  },
  {
    className:"ad-ring",
    title:"WEB RING INVITATION",
    icon:"O",
    body:"Join a ring of abandoned buttons, suspicious guestbooks, and heroic under-construction signs.",
    buttons:["surf sideways","next weird site","stay here"],
    fine:"All destinations are internal or imaginary."
  },
  {
    className:"ad-alert",
    title:"DESKTOP ALERT",
    icon:"!",
    body:"A desktop widget reports that the archive has exceeded recommended nonsense levels.",
    buttons:["acknowledge","open meter","ignore professionally"],
    fine:"This is a fake alert from a fake desktop."
  },
  {
    className:"ad-aquarium",
    title:"AQUARIUM SPONSOR",
    icon:"~",
    body:"The pixel aquarium requests browser crumbs and one small bubble budget increase.",
    buttons:["release bubbles","feed pixels","deny budget"],
    fine:"Pixel water is not drinkable."
  },
  {
    className:"ad-coupon",
    title:"CURSED COUPON",
    icon:"%",
    body:"Redeem this coupon for 0% off a mystery object that may already be in the archive.",
    buttons:["clip coupon","fold it wrong","summon receipt"],
    fine:"Coupon has no cash value, store value, or logical value."
  },
  {
    className:"ad-antivirus",
    title:"FAKE ANTIVIRUS SCAN",
    icon:"SCAN",
    body:"A theatrical scan found several harmless vibe irregularities.",
    buttons:["scan feelings","quarantine coupon","ignore professionally"],
    fine:"No real scan is running. This is a parody status window."
  },
  {
    className:"ad-psychic",
    title:"PSYCHIC POPUP HOTLINE",
    icon:"ORB",
    body:"The crystal modem predicts a button will be pressed soon.",
    buttons:["hear prophecy","decline prophecy","ask the static"],
    fine:"Prophecies are generated by dramatic CSS, not destiny."
  },
  {
    className:"ad-cursor",
    title:"LOST CURSOR RECOVERY",
    icon:"PTR",
    body:"Missing cursor last seen near the close button, acting suspicious.",
    buttons:["recover cursor","print poster","check under toolbar"],
    fine:"Cursor recovery is fictional. Your real pointer is fine."
  },
  {
    className:"ad-dust",
    title:"PREMIUM DUST SUBSCRIPTION",
    icon:"DUST",
    body:"Upgrade your archive shelves with artisanal CRT dust tiers.",
    buttons:["increase dust tier","sample premium dust","stay dusty"],
    fine:"Dust is metaphorical and should not be inhaled."
  },
  {
    className:"ad-bolt-insurance",
    title:"MYSTERY BOLT INSURANCE",
    icon:"BOLT",
    body:"Protect spare hardware from emotional uncertainty.",
    buttons:["polish bolt","accept fake risk","inspect policy"],
    fine:"Coverage is emotional only. No real insurance is offered."
  },
  {
    className:"ad-dialup",
    title:"DIAL-UP SPEED BOOSTER",
    icon:"56K",
    body:"Boost your imaginary modem from slow to slightly louder.",
    buttons:["boost beeps","test kb/s","cancel handshake"],
    fine:"No network settings are changed. The modem noise is implied."
  },
  {
    className:"ad-screensaver",
    title:"HAUNTED SCREENSAVER OFFER",
    icon:"CRT",
    body:"Install a fake bouncing shape that remembers your tabs.",
    buttons:["preview haunt","bounce ASCII","reject glow"],
    fine:"No files are installed. The haunt is decorative."
  },
  {
    className:"ad-chainmail",
    title:"FAKE EMAIL CHAIN LETTER",
    icon:"FWD",
    body:"Forward this to 404 friends or your toolbar gets lonely.",
    buttons:["forward to nobody","break chain","comfort toolbar"],
    fine:"This sends nothing. Chain letters belong in museums."
  },
  {
    className:"ad-pet",
    title:"PIXEL PET ADOPTION CENTER",
    icon:"PET",
    body:"Several small desktop creatures are seeking a temporary browser floor.",
    buttons:["adopt pixel crab","feed pet dust","open tiny cage"],
    fine:"Pets are tiny page effects. No animals, no accounts."
  },
  {
    className:"ad-loading-upgrade",
    title:"LOADING BAR UPGRADE",
    icon:"99%",
    body:"Make your loading bars look busier while accomplishing less.",
    buttons:["upgrade loading bar","unstick 99%","add stripes"],
    fine:"Progress remains fictional and emotionally unstable."
  },
  {
    className:"ad-weather-alert",
    title:"WEIRD WEATHER ALERT",
    icon:"WX",
    body:"Popup humidity is rising across Static City and Toolbar Swamp.",
    buttons:["refresh fake weather","collect drizzle","ignore forecast"],
    fine:"This forecast is not meteorological advice."
  },
  {
    className:"ad-vhs",
    title:"VHS TAPE CLUB",
    icon:"VHS",
    body:"Rent three haunted tapes and rewind none of them.",
    buttons:["rewind tape","rent static","pay fake fee"],
    fine:"No rentals occur. Rewind fees are purely theatrical."
  },
  {
    className:"ad-optimizer",
    title:"FAKE SYSTEM OPTIMIZER",
    icon:"OPT",
    body:"Optimize vibes, defragment buttons, and polish table cells.",
    buttons:["defragment vibes","inspect toolbar","optimize nothing"],
    fine:"No system settings are touched. Only jokes are optimized."
  },
  {
    className:"ad-goblin",
    title:"COUPON GOBLIN NOTICE",
    icon:"GOB",
    body:"A tiny coupon goblin stamped your browser with zero percent savings.",
    buttons:["summon coupon goblin","accept stamp","sweep coupon dust"],
    fine:"Goblin activity is fictional and coupon value is zero."
  },
  {
    className:"ad-cookie",
    title:"BROWSER FORTUNE COOKIE",
    icon:"COOKIE",
    body:"Crack open a fake browser fortune with lucky numbers 404, 98, and 13.7.",
    buttons:["open cookie","save lucky numbers","claim nothing"],
    fine:"No tracking cookies are created by this fortune."
  }
];

function clean(text){
  return String(text).replace(/[<>&]/g,(char)=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[char]));
}

function readJSON(key,fallback){
  try{return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback))}
  catch{return fallback}
}

function writeJSON(key,value){
  localStorage.setItem(key,JSON.stringify(value));
}

const inventoryCatalog = {
  "Mystery Bolt":{rarity:"odd",desc:"A spare bolt with no known source and too much confidence."},
  "Expired Banner Ad":{rarity:"stale",desc:"Still blinking after the offer ended."},
  "CRT Dust":{rarity:"common",desc:"Fine glowing powder from the scanline shelf."},
  "404 Shard":{rarity:"sharp",desc:"A tiny broken piece of not-found."},
  "Tiny Modem":{rarity:"rare",desc:"Screams quietly when placed near a coupon."},
  "Cursed Coupon":{rarity:"cursed",desc:"Worth zero percent off something imaginary."},
  "Loose Pixel":{rarity:"common",desc:"Keeps escaping the monitor border."},
  "Broken Loading Bar":{rarity:"unreliable",desc:"Never reaches 100 unless nobody is watching."},
  "Aquarium Bubble":{rarity:"wet",desc:"A bubble from the pixel tank."},
  "Fake Toolbar":{rarity:"sticky",desc:"Adds no features and three feelings."},
  "Haunted Floppy":{rarity:"vintage",desc:"Labeled FINAL_REAL_USE_THIS."},
  "Static Coin":{rarity:"currency",desc:"A coin with radio fuzz stamped on it."},
  "Popup Buck":{rarity:"currency",desc:"Legal tender inside no real economy."},
  "Coupon Dust":{rarity:"currency",desc:"Powdered savings, do not inhale."},
  "VDO Spark":{rarity:"bright",desc:"Fell off the bouncing signal blob."},
  "Emergency Panic Receipt":{rarity:"official",desc:"Proof that panic failed successfully."},
  "Desktop Crab Shell":{rarity:"desktop",desc:"A tiny shell from a taskbar incident."},
  "Radio Static Sample":{rarity:"audio",desc:"Stored in a jar labeled CH 404."},
  "Weather Pixel":{rarity:"forecast",desc:"Partly cloudy with a chance of blinking."},
  "Fake Patch Note":{rarity:"update",desc:"Claims to fix one issue by creating three."}
};

const achievementCatalog = {
  popupPest:{name:"Popup Pest Control",desc:"Close 10 fake ads."},
  adStormSurvivor:{name:"Ad Storm Survivor",desc:"Start ad storm."},
  secretDoor:{name:"Secret Door Opener",desc:"Unlock ???."},
  pixelHunter:{name:"Pixel Hunter",desc:"Find the hidden pixel."},
  aquariumGoblin:{name:"Aquarium Goblin",desc:"Feed the aquarium."},
  panicBeliever:{name:"Panic Believer",desc:"Press the panic button."},
  staticEnjoyer:{name:"Static Enjoyer",desc:"Trigger 5 random events."},
  buttonGremlin:{name:"Button Gremlin",desc:"Click 100 buttons."},
  chaosTechnician:{name:"Chaos Technician",desc:"Set chaos level to dial-up apocalypse."},
  vdoWitness:{name:"VDO Witness",desc:"Keep the site open long enough to watch the signal bounce."},
  fileGoblin:{name:"File Goblin",desc:"Open 10 fake files."},
  radioDrifter:{name:"Radio Drifter",desc:"Tune 5 fake stations."},
  weatherLiar:{name:"Weather Liar",desc:"Refresh fake weather 5 times."},
  patchSurvivor:{name:"Patch Survivor",desc:"Survive a fake update failure."},
  shopVictim:{name:"Shop Victim",desc:"Buy any fake shop item."},
  deeperArchive:{name:"Deeper Archive",desc:"Unlock the second secret phrase."}
};

const currencyNames = ["Static Coins","Popup Bucks","Coupon Dust"];
const chaosLabels = ["calm","weird","annoying","haunted","dial-up apocalypse"];
const questPhrase = "bolt-coupon-vhs";

function getInventory(){return readJSON("oddInventory",{})}
function getAchievements(){return readJSON("oddAchievements",{})}
function getCurrency(){return readJSON("oddCurrency",{"Static Coins":0,"Popup Bucks":0,"Coupon Dust":0})}
function getPurchases(){return readJSON("oddShopPurchases",{})}
function getQuest(){return readJSON("oddQuest",{})}
function getChaosLevel(){return Math.max(0,Math.min(4,Number(localStorage.getItem("oddChaosLevel") || 1)))}

function setStatusText(selector,text){
  $$(selector).forEach((el)=>el.textContent = text);
}

function addInventoryItem(itemName,amount=1){
  const inv = getInventory();
  inv[itemName] = (Number(inv[itemName]) || 0) + amount;
  writeJSON("oddInventory",inv);
  localStorage.setItem("oddLatestItem",itemName);
  updateArchiveDashboard();
  return inv[itemName];
}

function addCurrency(type,amount=1){
  const currency = getCurrency();
  currency[type] = (Number(currency[type]) || 0) + amount;
  writeJSON("oddCurrency",currency);
  updateArchiveDashboard();
}

function incrementStat(key,amount=1){
  const n = Number(localStorage.getItem(key) || 0) + amount;
  localStorage.setItem(key,String(n));
  return n;
}

function unlockAchievement(id){
  if(!achievementCatalog[id]) return false;
  const achievements = getAchievements();
  if(achievements[id]) return false;
  achievements[id] = {unlocked:true,date:new Date().toLocaleString()};
  writeJSON("oddAchievements",achievements);
  showAchievementToast(achievementCatalog[id].name);
  updateArchiveDashboard();
  return true;
}

function showAchievementToast(name){
  const toast = document.createElement("div");
  toast.className = "achievement-toast";
  toast.innerHTML = `<b>ACHIEVEMENT UNLOCKED</b><br>${clean(name)}`;
  document.body.appendChild(toast);
  setTimeout(()=>toast.remove(),4200);
  playSound("confetti");
}

function setChaosLevel(level){
  const next = Math.max(0,Math.min(4,Number(level)));
  localStorage.setItem("oddChaosLevel",String(next));
  if(next === 4) unlockAchievement("chaosTechnician");
  updateChaosControls();
  updateArchiveDashboard();
}

function updateChaosControls(){
  const level = getChaosLevel();
  $$(".chaos-slider").forEach((input)=>input.value = String(level));
  setStatusText("[data-chaos-status]",`Chaos level ${level}: ${chaosLabels[level]}`);
}

function getChaosMultiplier(){
  return 1 + getChaosLevel() * .35;
}

function countInventoryItems(){
  return Object.values(getInventory()).reduce((sum,n)=>sum + Number(n || 0),0);
}

function countAchievements(){
  return Object.keys(getAchievements()).length;
}

function currencySummary(){
  const currency = getCurrency();
  return currencyNames.map((name)=>`${name}: ${Number(currency[name] || 0)}`).join(" | ");
}

function updateArchiveDashboard(){
  const level = getChaosLevel();
  setStatusText("[data-dashboard-chaos]",`${level} - ${chaosLabels[level]}`);
  setStatusText("[data-dashboard-event]",localStorage.getItem("oddLatestEvent") || "none yet");
  setStatusText("[data-dashboard-inventory]",String(countInventoryItems()));
  setStatusText("[data-dashboard-achievements]",`${countAchievements()} / ${Object.keys(achievementCatalog).length}`);
  setStatusText("[data-dashboard-currency]",currencySummary());
  setStatusText("[data-dashboard-item]",localStorage.getItem("oddLatestItem") || "nothing collected yet");
  setStatusText("[data-dashboard-mood]",archiveMood());
}

function archiveMood(){
  return ["sleepy static","button confidence rising","popup humidity high","fish tank suspicious","coupon pressure unstable"][Math.floor(Math.random()*5)];
}

function awardRandomJunk(reason="interaction"){
  const items = Object.keys(inventoryCatalog);
  const item = items[Math.floor(Math.random()*items.length)];
  addInventoryItem(item,1);
  if(reason === "ad") addCurrency("Popup Bucks",1);
  else if(reason === "event") addCurrency("Static Coins",1);
  else if(reason === "coupon") addCurrency("Coupon Dust",1);
  else addCurrency(currencyNames[Math.floor(Math.random()*currencyNames.length)],1);
  return item;
}

function closeAllPopupAds(){
  const ads = $$(".popup-ad");
  ads.forEach((ad)=>ad.remove());
  return ads.length;
}

function popupsAreMuted(){
  return localStorage.getItem("oddPopupsDisabled") === "true";
}

function updatePopupMuteButton(){
  const muted = popupsAreMuted();
  $$(".quiet-signal-toggle").forEach((button)=>{
    button.textContent = muted ? "quiet signal: on" : "quiet signal";
    button.setAttribute("aria-pressed",String(muted));
    button.title = muted ? "Random fake popups are muted." : "Quiet the random fake popup system.";
  });
}

function togglePopupMute(){
  const next = !popupsAreMuted();
  localStorage.setItem("oddPopupsDisabled",String(next));
  if(next){
    adStorm = false;
    clearTimeout(adStormTimer);
    clearTimeout(randomAdTimer);
    closeAllPopupAds();
    latestEvent("The archive lowered popup pressure.");
  }
  else {
    latestEvent("Popup pressure restored. The archive is blinking again.");
    scheduleNextRandomAd(true);
  }
  updatePopupMuteButton();
  updateAdStormButton();
}

function spawnPanicAd(count){
  const ad = document.createElement("div");
  ad.className = "popup-ad ad-alert panic-ad";
  const html = `<div class="ad-title"><span>! PANIC SYSTEM</span><button class="x" title="close">X</button></div><div class="ad-body system-alert"><div class="alert-icon">!</div><div><b>panic acknowledged, one emergency popup remains.</b><p>${count} popup(s) removed. Panic mode failed successfully.</p><p><button>accept receipt</button><button>panic again later</button></p><p class="ad-fine">This is a fake theatrical system notice.</p></div></div>`;
  ad.innerHTML = html;
  verifyPopupMarkup(ad,html,"panic-ad");
  document.body.appendChild(ad);
  positionPopupSafely(ad,"panic-ad");
  ad.querySelector(".x").onclick = () => {
    awardAdClose();
    ad.remove();
  };
  ad.querySelectorAll(".ad-body button").forEach((button)=>button.onclick = () => spawnSticker());
  makeDraggable(ad,ad.querySelector(".ad-title"));
}

function panicButton(){
  const closed = closeAllPopupAds();
  addInventoryItem("Emergency Panic Receipt",1);
  addCurrency("Popup Bucks",Math.max(1,closed));
  unlockAchievement("panicBeliever");
  playSound("alarm");
  spawnPanicAd(closed);
  updateArchiveDashboard();
}

function awardAdClose(){
  addInventoryItem("Expired Banner Ad",1);
  addCurrency("Popup Bucks",1);
  const closed = incrementStat("oddClosedAds",1);
  if(closed >= 10) unlockAchievement("popupPest");
}

function addQuestClue(id,text){
  const quest = getQuest();
  if(!quest[id]){
    quest[id] = {text,date:new Date().toLocaleString()};
    writeJSON("oddQuest",quest);
    addInventoryItem("404 Shard",1);
  }
  renderQuestClues();
}

function renderQuestClues(){
  const quest = getQuest();
  const list = $("#questClues");
  if(!list) return;
  list.innerHTML = Object.entries(quest).map(([id,data])=>`<li><b>${clean(id)}</b>: ${clean(data.text)}</li>`).join("") || "<li>No clue fragments recovered yet.</li>";
}

function unlockDeeperArchive(){
  const input = $("#deeperPhrase");
  const out = $("#deeperOut");
  const panel = $("#deeperArchivePanel");
  if(!input || !out || !panel) return;
  if(input.value.trim().toLowerCase() === questPhrase){
    panel.classList.add("unlocked");
    out.textContent = "DEEPER ARCHIVE OPEN: phrase accepted.";
    addInventoryItem("VDO Spark",2);
    addCurrency("Static Coins",25);
    unlockAchievement("deeperArchive");
    playSound("secret");
  }else{
    out.textContent = "Phrase rejected. The archive coughs up static.";
    playSound("buzz");
  }
}

function latestEvent(text){
  localStorage.setItem("oddLatestEvent",text);
  setStatusText("[data-latest-event]",text);
  updateArchiveDashboard();
}

function signalBanner(text){
  const banner = document.createElement("div");
  banner.className = "signal-banner";
  banner.textContent = text;
  document.body.appendChild(banner);
  setTimeout(()=>banner.remove(),5200);
}

function spawnFallingCoupon(){
  const coupon = document.createElement("div");
  coupon.className = "falling-coupon";
  coupon.textContent = "0% OFF";
  coupon.style.left = Math.random()*90 + "vw";
  document.body.appendChild(coupon);
  setTimeout(()=>coupon.remove(),5200);
}

function triggerRandomEvent(){
  const events = [
    ()=>{document.body.classList.add("static-burst");setTimeout(()=>document.body.classList.remove("static-burst"),1800);latestEvent("Static burst rattled the archive.");},
    ()=>{document.body.classList.add("page-shake");setTimeout(()=>document.body.classList.remove("page-shake"),900);latestEvent("Page shake from unstable table layout.");},
    ()=>{openFakeWindow("Random System Alert","The archive noticed a suspicious amount of normal behavior.");latestEvent("Fake system alert appeared.");},
    ()=>{const msg = "Mystery bolt speaks: turn left at the coupon."; latestEvent(msg); signalBanner(msg); addInventoryItem("Mystery Bolt",1);},
    ()=>{latestEvent("Aquarium leak warning issued."); signalBanner("AQUARIUM LEAK WARNING: water is mostly CSS."); addInventoryItem("Aquarium Bubble",1);},
    ()=>{document.body.classList.toggle("nightmare");setTimeout(()=>document.body.classList.toggle("nightmare"),3200);latestEvent("Background hue shifted without paperwork.");},
    ()=>{spawnSticker();latestEvent("One weird sticker entered the evidence room.");},
    ()=>{spawnAd(false);latestEvent("Random popup specimen escaped.");},
    ()=>{signalBanner("SIGNAL INTERRUPTION: PLEASE CLAP FOR THE LOADING BAR");latestEvent("Signal interruption banner broadcast.");},
    ()=>{spawnDesktopPet();latestEvent("Desktop pet crossed the page.");},
    ()=>{spawnFallingCoupon();latestEvent("Fake coupon fell from the browser ceiling.");addInventoryItem("Cursed Coupon",1);}
  ];
  events[Math.floor(Math.random()*events.length)]();
  const n = incrementStat("oddRandomEvents",1);
  addCurrency("Static Coins",1);
  awardRandomJunk("event");
  if(n >= 5) unlockAchievement("staticEnjoyer");
}

function startRandomEventEngine(){
  const delay = Math.max(9000,80000 - getChaosLevel()*15000) + Math.random() * Math.max(12000,30000 - getChaosLevel()*4000);
  setTimeout(()=>{
    triggerRandomEvent();
    startRandomEventEngine();
  },delay);
}

function spawnDesktopPet(type){
  const types = {
    crab:{label:"(V)V",item:"Desktop Crab Shell",msg:"pixel crab clicks in square brackets"},
    modem:{label:"56K",item:"Tiny Modem",msg:"tiny modem whispers carrier tone"},
    cursor:{label:"PTR",item:"Loose Pixel",msg:"loose cursor points at nothing"},
    vdo:{label:"vdo",item:"VDO Spark",msg:"mini VDO baby bounces badly"},
    coupon:{label:"BUG",item:"Cursed Coupon",msg:"coupon bug requests a discount"},
    toolbar:{label:"TB",item:"Fake Toolbar",msg:"toolbar worm adds a useless button"}
  };
  const keys = Object.keys(types);
  const pet = types[type] || types[keys[Math.floor(Math.random()*keys.length)]];
  const el = document.createElement("button");
  el.className = "desktop-pet";
  el.textContent = pet.label;
  el.style.left = "-60px";
  el.style.top = 80 + Math.random() * Math.max(120,innerHeight - 180) + "px";
  el.onclick = () => {
    addInventoryItem(pet.item,1);
    latestEvent(pet.msg);
    playSound("blip");
    el.remove();
  };
  document.body.appendChild(el);
  incrementStat("oddPetsSpawned",1);
  setTimeout(()=>{if(el.isConnected)el.remove()},12000);
  return el;
}

function enhanceSiteControls(){
  $$(".box").forEach((box)=>{
    const heading = box.querySelector("h3");
    if(!heading || heading.textContent.trim().toLowerCase() !== "site controls") return;
    if(!box.querySelector("[data-panic-button]")){
      const panic = document.createElement("button");
      panic.type = "button";
      panic.dataset.panicButton = "true";
      panic.dataset.sound = "alarm";
      panic.textContent = "PANIC BUTTON";
      panic.onclick = panicButton;
      box.appendChild(panic);
    }
    if(!box.querySelector("[data-pet-button]")){
      const pet = document.createElement("button");
      pet.type = "button";
      pet.dataset.petButton = "true";
      pet.textContent = "spawn desktop pet";
      pet.onclick = () => spawnDesktopPet();
      box.appendChild(pet);
    }
    if(!box.querySelector(".quiet-signal-toggle")){
      const quiet = document.createElement("button");
      quiet.type = "button";
      quiet.className = "quiet-signal-toggle";
      quiet.onclick = togglePopupMute;
      box.appendChild(quiet);
    }
    if(!box.querySelector(".chaos-control")){
      const wrap = document.createElement("div");
      wrap.className = "chaos-control";
      wrap.innerHTML = `<label>chaos level <input class="chaos-slider" type="range" min="0" max="4" step="1"></label><p data-chaos-status></p><p class="mini-status">Inventory: <span data-dashboard-inventory>0</span> | Achievements: <span data-dashboard-achievements>0</span></p>`;
      box.appendChild(wrap);
      wrap.querySelector(".chaos-slider").oninput = (e)=>setChaosLevel(e.target.value);
    }
  });
  updatePopupMuteButton();
  updateChaosControls();
}

function ensureExpandedNav(){
  $$(".nav").forEach((nav)=>{
    const isRoot = location.pathname.endsWith("/") || location.pathname.endsWith("index.html") || !location.pathname.includes("/pages/");
    const prefix = isRoot ? "pages/" : "";
    const homeHref = isRoot ? "index.html" : "../index.html";
    const links = [
      ["Home",homeHref],["Signal Archive",prefix+"about.html"],["Tiny Games",prefix+"games.html"],["Random Junk",prefix+"random.html"],["Impossible Garage",prefix+"cars.html"],["Chaos Lab",prefix+"lab.html"],["Fake Desktop",prefix+"desktop.html"],["Pixel Aquarium",prefix+"aquarium.html"],["Web Ring",prefix+"webring.html"],["Guestbook",prefix+"guestbook.html"],["???",prefix+"secrets.html"],["Loading Void",prefix+"void.html"],["Fake Ad Museum",prefix+"ads.html"],["Mystery Bolt Oracle",prefix+"oracle.html"],["Object Shrine",prefix+"objects.html"],["Broken CRT",prefix+"tv.html"],["Useless Buttons",prefix+"buttons.html"],["Tiny Link Maze",prefix+"maze.html"],["Inventory",prefix+"inventory.html"],["Achievements",prefix+"achievements.html"],["Cursed File Explorer",prefix+"files.html"],["Cursed Search",prefix+"search.html"],["Lost Pages",prefix+"lost.html"],["ArchiveBot 98",prefix+"bot.html"],["Radio",prefix+"radio.html"],["Fake Weather",prefix+"weather.html"],["Fake Update",prefix+"update.html"],["Shop",prefix+"shop.html"]
    ];
    if(!nav.querySelector("[data-expanded-nav]")){
      const marker = document.createElement("small");
      marker.dataset.expandedNav = "true";
      marker.textContent = "toybox systems";
      nav.appendChild(marker);
    }
    links.forEach(([label,path])=>{
      const href = prefix + path;
      if(!nav.querySelector(`a[href="${href}"]`) && !Array.from(nav.querySelectorAll("a")).some((a)=>a.textContent.trim() === label)){
        const a = document.createElement("a");
        a.href = href;
        a.textContent = label;
        nav.appendChild(a);
      }
    });
  });
}

function clickPuff(x,y){
  const count = 4 + getChaosLevel() * 2;
  for(let i=0;i<count;i++){
    const bit = document.createElement("span");
    bit.className = "click-puff";
    bit.textContent = puffBits[Math.floor(Math.random() * puffBits.length)];
    const angle = (Math.PI * 2 * i / count) + Math.random() * .55;
    const distance = 18 + Math.random() * 28;
    bit.style.left = x + "px";
    bit.style.top = y + "px";
    bit.style.setProperty("--dx",Math.cos(angle) * distance + "px");
    bit.style.setProperty("--dy",Math.sin(angle) * distance + "px");
    bit.style.color = `hsl(${Math.random() * 360},100%,72%)`;
    document.body.appendChild(bit);
    setTimeout(()=>bit.remove(),520);
  }
}

function getAudioContext(){
  if(!audioContext){
    const AudioCtx = window.AudioContext || window.webkitAudioContext;
    if(!AudioCtx) return null;
    audioContext = new AudioCtx();
  }
  if(audioContext.state === "suspended") audioContext.resume();
  return audioContext;
}

function tone(ctx,freq,start,duration,type="square",volume=.045){
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq,start);
  gain.gain.setValueAtTime(0,start);
  gain.gain.linearRampToValueAtTime(volume,start + .01);
  gain.gain.exponentialRampToValueAtTime(.0001,start + duration);
  osc.connect(gain).connect(ctx.destination);
  osc.start(start);
  osc.stop(start + duration + .03);
}

function playSound(type="beep"){
  if(!soundEnabled) return;
  const ctx = getAudioContext();
  if(!ctx) return;
  const now = ctx.currentTime;
  const patterns = {
    nav:[[520,0,.035,"triangle",.025]],
    blip:[[680,0,.045,"square",.035],[940,.045,.04,"square",.025]],
    pop:[[260,0,.035,"sine",.05],[120,.035,.045,"sine",.03]],
    coin:[[784,0,.045,"square",.04],[1046,.055,.06,"square",.035]],
    secret:[[155,0,.11,"sawtooth",.035],[196,.09,.12,"triangle",.03]],
    buzz:[[90,0,.12,"sawtooth",.05],[74,.05,.12,"sawtooth",.04]],
    confetti:[[523,0,.04,"triangle",.035],[659,.045,.04,"triangle",.035],[784,.09,.06,"triangle",.035]],
    alarm:[[440,0,.055,"square",.035],[330,.07,.055,"square",.035],[440,.14,.055,"square",.035]],
    wobble:[[220,0,.07,"sine",.035],[280,.07,.07,"sine",.035],[210,.14,.08,"sine",.03]],
    beep:[[620,0,.045,"square",.035]]
  };
  (patterns[type] || patterns.beep).forEach(([freq,offset,duration,wave,volume])=>tone(ctx,freq,now+offset,duration,wave,volume));
}

function resolveSoundType(target){
  const explicit = target.closest("[data-sound]");
  if(explicit) return explicit.dataset.sound;
  if(target.closest(".popup-ad .x,.fake-window .x")) return "pop";
  if(target.closest(".popup-ad button")) return "blip";
  if(target.closest(".nav a")) return "nav";
  if(target.closest("#secretPanel,#secretPassword") || /unlock|secret|ritual/i.test(target.textContent || "")) return "secret";
  if(target.closest(".mini-game,.captcha-grid,.memory-grid") || /arcade|reaction|captcha|mole|pixel|memory|roulette|fortune|game|coin/i.test(target.textContent || "")) return "coin";
  if(target.closest("[data-ad-storm]")) return "alarm";
  if(target.closest("[data-spin-toggle]")) return "wobble";
  if(/confetti|overdo|chaos/i.test(target.textContent || "")) return "confetti";
  if(target.closest("a")) return "nav";
  if(target.closest("button")) return "beep";
  return "beep";
}

function attachGlobalClickEffects(){
  document.addEventListener("click",(e)=>{
    const target = e.target;
    if(target.closest(".ad-title,.win-title") && !target.closest("button")) return;
    clickPuff(e.clientX,e.clientY);
    if(Math.random() < getChaosLevel() * .04) spawnSticker();
    if(getChaosLevel() >= 3 && Math.random() < .012) spawnDesktopPet();
    if(target.closest("button")){
      const clicks = incrementStat("oddButtonClicks",1);
      if(clicks >= 100) unlockAchievement("buttonGremlin");
    }
    if(target.closest("button,a,input,select,textarea,.mini-game,.fake-desktop")) playSound(resolveSoundType(target));
    if(Math.random() < getChaosLevel() * .025) playSound("blip");
  },true);
}

function updateSoundButton(){
  $$(".sound-toggle").forEach((button)=>{
    button.textContent = soundEnabled ? "sound on" : "sound off";
    button.setAttribute("aria-pressed",String(soundEnabled));
  });
}

function toggleSound(){
  soundEnabled = !soundEnabled;
  localStorage.setItem("oddSoundEnabled",String(soundEnabled));
  updateSoundButton();
  if(soundEnabled) playSound("blip");
}

function addSoundToggle(){
  $$(".box").forEach((box)=>{
    const heading = box.querySelector("h3");
    if(!heading || heading.textContent.trim().toLowerCase() !== "site controls" || box.querySelector(".sound-toggle")) return;
    const button = document.createElement("button");
    button.type = "button";
    button.className = "sound-toggle";
    button.dataset.sound = "blip";
    button.onclick = toggleSound;
    box.appendChild(button);
  });
  updateSoundButton();
}

function visitorCounter(){
  const key = "oddFrequencyVisitors";
  const n = Number(localStorage.getItem(key) || 0) + 1;
  localStorage.setItem(key,String(n));
  const el = $("#counter");
  if(el) el.textContent = String(n).padStart(8,"0");
}

function randomQuote(){
  const quotes = [
    "Archive note: the fake ads are restless tonight.",
    "A blinking button was cataloged and immediately escaped.",
    "Signal quality: bent but oddly charming.",
    "Do not feed the mystery bolt after midnight.",
    "A tiny game cabinet is humming behind the wallpaper.",
    "This page is best viewed with one tab too many.",
    "The bouncing logo is practicing for the corner hit."
  ];
  const el = $("#quote");
  if(el) el.textContent = quotes[Math.floor(Math.random() * quotes.length)];
}

function spawnConfetti(){
  for(let i = 0; i < 85; i++){
    const d = document.createElement("div");
    d.className = "confetti-bit";
    d.textContent = ["*","+","x","o","#","%","=","~"][Math.floor(Math.random() * 8)];
    Object.assign(d.style,{
      left:Math.random() * 100 + "vw",
      fontSize:12 + Math.random() * 30 + "px",
      color:`hsl(${Math.random() * 360},100%,70%)`
    });
    document.body.appendChild(d);
    let y = 0;
    let rot = Math.random() * 180;
    const speed = 3 + Math.random() * 6;
    const wobble = Math.random() * 50;
    const id = setInterval(()=>{
      y += speed;
      rot += 10 + Math.random() * 12;
      d.style.transform = `translate(${Math.sin(y / 35) * wobble}px, ${y}px) rotate(${rot}deg)`;
      if(y > innerHeight + 80){
        clearInterval(id);
        d.remove();
      }
    },28);
  }
}

function spawnSticker(){
  const d = document.createElement("div");
  d.className = "sticker";
  d.textContent = stickerBits[Math.floor(Math.random() * stickerBits.length)];
  d.style.left = Math.random() * 90 + "vw";
  d.style.top = Math.random() * 85 + "vh";
  d.style.color = `hsl(${Math.random() * 360},100%,72%)`;
  document.body.appendChild(d);
  setTimeout(()=>d.remove(),2700);
}

function adMarkup(template){
  const body = clean(template.body);
  const fine = clean(template.fine);
  const buttons = template.buttons.map((label)=>`<button>${clean(label)}</button>`).join("");
  const title = `<div class="ad-title"><span>${clean(template.icon)} ${clean(template.title)}</span><button class="x" title="close">X</button></div>`;
  if(template.className === "ad-prize"){
    return `${title}<div class="ad-body"><div class="ad-burst">WINNER-ISH!</div><b>${body}</b><p class="ad-loud">Claim one imaginary trophy and a lifetime supply of blinking.</p><div class="winner-number">CERTIFICATE #${Math.floor(10000 + Math.random()*89999)}</div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-toolbar"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="fake-checkboxes"><label><input type="checkbox" checked> Weather Wormhole</label><label><input type="checkbox" checked> Coupon Radar</label><label><input type="checkbox"> Emotionally Gray Buttons</label></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-fortune"){
    return `${title}<div class="ad-body"><div class="starscope">*  MODEM HOROSCOPE  *</div><b>${body}</b><p>Your rising sign is: abandoned web ring.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-banner"){
    return `${title}<div class="ad-body"><div class="dance-line"><<< DANCE CLICK DANCE CLICK DANCE >>></div><b>${body}</b><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-download"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="download-file">File: nothing_${Math.floor(Math.random()*900+100)}.zip<br>Speed: ${Math.floor(Math.random()*48+3)} kb/s<br>Status: theatrically paused</div><div class="fake-progress"></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-visitor"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="visitor-certificate"><span>${String(Math.floor(100000 + Math.random()*899999))}</span><small>LOCAL FAKE VISITOR CERTIFICATE</small></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-ring"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="ring-buttons"><button>PREV</button><button>RANDOM</button><button>NEXT</button></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-alert"){
    return `${title}<div class="ad-body system-alert"><div class="alert-icon">!</div><div><b>${body}</b><p>Recommended action: acknowledge the nonsense.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div></div>`;
  }
  if(template.className === "ad-aquarium"){
    return `${title}<div class="ad-body"><div class="ad-water">o O o O o</div><b>${body}</b><p>Sponsored by bubbles that are definitely not sentient.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-coupon"){
    return `${title}<div class="ad-body coupon-body"><b>${body}</b><p>Clip along the imaginary dashed line.</p><div class="barcode">|||| ||| || ||||| | ||||</div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-antivirus"){
    return `${title}<div class="ad-body"><b>${body}</b><ul class="scan-list"><li>haunted cookie</li><li>unstable toolbar</li><li>lonely button</li><li>expired coupon cache</li></ul><div class="fake-progress"></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-psychic"){
    return `${title}<div class="ad-body"><div class="crystal-ball">O</div><b>${body}</b><p class="fortune-slip">Prophecy: the next popup will have opinions.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-cursor"){
    return `${title}<div class="ad-body"><div class="missing-poster"><b>MISSING</b><span>PTR</span><small>last seen near the close button</small></div><b>${body}</b><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-dust"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="tier-card"><span>Basic Dust</span><span>Premium Dust</span><span>Executive Dust</span></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-bolt-insurance"){
    return `${title}<div class="ad-body insurance-doc"><b>${body}</b><p>Policy #BOLT-${Math.floor(1000+Math.random()*8999)}</p><p>Coverage: emotional only</p><p>Deductible: one mystery washer</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-dialup"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="speed-meter"><span>14.4</span><span>28.8</span><span>56k-ish</span></div><div class="fake-progress"></div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-screensaver"){
    return `${title}<div class="ad-body"><div class="screensaver-box">&lt;*&gt;</div><b>${body}</b><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-chainmail"){
    return `${title}<div class="ad-body email-forward"><p>FWD: FWD: FWD: IMPORTANT ARCHIVE ENERGY</p><b>${body}</b><blockquote>send to 404 friends or your toolbar gets lonely</blockquote><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-pet"){
    return `${title}<div class="ad-body"><div class="pet-display">(V)V  56K  PTR</div><b>${body}</b><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-loading-upgrade"){
    return `${title}<div class="ad-body"><b>${body}</b><div class="multi-bars"><div style="width:31%"></div><div style="width:64%"></div><div style="width:99%"></div></div><p>One bar is contractually stuck.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-weather-alert"){
    return `${title}<div class="ad-body weather-alert-card"><b>${body}</b><p>Advisory: banner winds from the east, scattered coupon fog.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-vhs"){
    return `${title}<div class="ad-body"><div class="vhs-card">[ VHS ]<br>STATIC RENTAL CLUB</div><b>${body}</b><p>Late fee: one haunted floppy.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-optimizer"){
    return `${title}<div class="ad-body"><b>${body}</b><ul class="optimizer-list"><li>optimize vibes</li><li>defragment buttons</li><li>polish table layout</li><li>remove calm mode</li></ul><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-goblin"){
    return `${title}<div class="ad-body goblin-stamp"><b>${body}</b><div class="stamp">APPROVED 0% OFF</div><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  if(template.className === "ad-cookie"){
    return `${title}<div class="ad-body cookie-slip"><b>${body}</b><p>Your lucky files: 404, 98, 13.7</p><p>Fortune: close one popup, open three possibilities.</p><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
  }
  return `${title}<div class="ad-body"><b>${body}</b><p>${buttons}</p><p class="ad-fine">${fine}</p></div>`;
}

function getVisualViewportBox(){
  const vv = window.visualViewport;
  return {
    width: vv?.width || window.innerWidth,
    height: vv?.height || window.innerHeight,
    offsetLeft: vv?.offsetLeft || 0,
    offsetTop: vv?.offsetTop || 0
  };
}

function clampPopupPosition(element,preferredLeft,preferredTop,className=element.className,debug=false){
  const pad = 12;
  const viewport = getVisualViewportBox();
  let rect = element.getBoundingClientRect();
  let layoutWidth = element.offsetWidth || rect.width;
  let layoutHeight = element.offsetHeight || rect.height;
  if(layoutHeight < 100){
    element.style.minHeight = "190px";
    console.warn("[Odd Frequency] ad measured unusually short; forcing popup min-height", {className,height:layoutHeight});
    rect = element.getBoundingClientRect();
    layoutWidth = element.offsetWidth || rect.width;
    layoutHeight = element.offsetHeight || rect.height;
  }
  const width = Math.min(layoutWidth,Math.max(1,viewport.width - pad * 2));
  const height = Math.min(layoutHeight,Math.max(1,viewport.height - pad * 2));
  const minLeft = viewport.offsetLeft + pad;
  const minTop = viewport.offsetTop + pad;
  const maxLeft = Math.max(minLeft,viewport.offsetLeft + viewport.width - width - pad);
  const maxTop = rect.height >= viewport.height - pad * 2 ? minTop : Math.max(minTop,viewport.offsetTop + viewport.height - height - pad);
  const left = Math.round(Math.min(maxLeft,Math.max(minLeft,preferredLeft)));
  const top = Math.round(Math.min(maxTop,Math.max(minTop,preferredTop)));
  element.style.left = left + "px";
  element.style.top = top + "px";
  element.style.visibility = "visible";
  element.style.opacity = "1";
  if(debug) console.debug("[Odd Frequency] ad positioned", {className,width:layoutWidth,height:layoutHeight,left,top});
}

function forcePopupInternalsVisible(element, className){
if(!element) return;

element.style.visibility = "visible";
element.style.opacity = "1";

const title = element.querySelector(".ad-title");
const body = element.querySelector(".ad-body");
const close = element.querySelector(".x");

if(title){
title.style.display = "flex";
title.style.visibility = "visible";
title.style.opacity = "1";
title.style.minHeight = "32px";
}else{
console.warn("[Odd Frequency] popup missing title", {className});
}

if(body){
body.style.display = "block";
body.style.visibility = "visible";
body.style.opacity = "1";
body.style.minHeight = "130px";
body.style.overflowY = "auto";
body.style.color = body.style.color || "#000";
}else{
console.warn("[Odd Frequency] popup missing body", {className});
}

if(close){
close.style.display = "inline-block";
close.style.visibility = "visible";
close.style.opacity = "1";
}else{
console.warn("[Odd Frequency] popup missing close button", {className});
}

if(title && title.getBoundingClientRect().height < 20){
console.warn("[Odd Frequency] ad title too short", {className});
title.style.minHeight = "32px";
}

if(body && body.getBoundingClientRect().height < 60){
console.warn("[Odd Frequency] ad body too short", {className});
body.style.minHeight = "130px";
}
}

function positionPopupSafely(element,className=element.className){
  const pad = 12;
  const viewport = getVisualViewportBox();
  element.style.visibility = "visible";
  element.style.opacity = "0";
  element.style.left = viewport.offsetLeft + pad + "px";
  element.style.top = viewport.offsetTop + pad + "px";
  const rect = element.getBoundingClientRect();
  const safeWidth = Math.min(element.offsetWidth || rect.width || 360,Math.max(1,viewport.width - pad * 2));
  const safeHeight = Math.min(Math.max(element.offsetHeight || rect.height || 190,190),Math.max(1,viewport.height - pad * 2));
  const maxLeft = Math.max(viewport.offsetLeft + pad,viewport.offsetLeft + viewport.width - safeWidth - pad);
  const maxTop = Math.max(viewport.offsetTop + pad,viewport.offsetTop + viewport.height - safeHeight - pad);
  const left = viewport.offsetLeft + pad + Math.random() * Math.max(0,maxLeft - (viewport.offsetLeft + pad));
  const top = viewport.offsetTop + pad + Math.random() * Math.max(0,maxTop - (viewport.offsetTop + pad));
  clampPopupPosition(element,left,top,className,true);
  forcePopupInternalsVisible(element,className);
  requestAnimationFrame(()=>{
    clampPopupPosition(element,parseFloat(element.style.left) || left,parseFloat(element.style.top) || top,className,true);
    forcePopupInternalsVisible(element,className);
  });
  setTimeout(()=>{
    if(element.isConnected){
      clampPopupPosition(element,parseFloat(element.style.left) || left,parseFloat(element.style.top) || top,className,true);
      forcePopupInternalsVisible(element,className);
    }
  },240);
}

function awardAdTemplateReward(template){
  const rewards = {
    "ad-coupon":["Cursed Coupon","Coupon Dust"],
    "ad-goblin":["Cursed Coupon","Coupon Dust"],
    "ad-antivirus":["Fake Toolbar","CRT Dust"],
    "ad-optimizer":["Fake Toolbar","CRT Dust"],
    "ad-weather-alert":["Weather Pixel"],
    "ad-vhs":["Haunted Floppy"],
    "ad-dialup":["Tiny Modem"],
    "ad-cursor":["Loose Pixel"],
    "ad-bolt-insurance":["Mystery Bolt"],
    "ad-loading-upgrade":["Broken Loading Bar"],
    "ad-aquarium":["Aquarium Bubble"],
    "ad-pet":["Desktop Crab Shell"],
    "ad-dust":["CRT Dust"],
    "ad-screensaver":["VDO Spark","Radio Static Sample"]
  };
  const pool = rewards[template.className] || ["Popup Buck","CRT Dust","Expired Banner Ad"];
  const reward = pool[Math.floor(Math.random()*pool.length)];
  if(reward === "Coupon Dust") addCurrency("Coupon Dust",1);
  else if(reward === "Popup Buck") addCurrency("Popup Bucks",1);
  else addInventoryItem(reward,1);
}

function verifyPopupMarkup(ad, html, className){
console.debug("[Odd Frequency] ad html generated", {
className,
length: html.length,
hasTitle: !!ad.querySelector(".ad-title"),
hasBody: !!ad.querySelector(".ad-body")
});

if(!ad.querySelector(".ad-title") || !ad.querySelector(".ad-body")){
console.warn("[Odd Frequency] ad template failed, using fallback", {className});
ad.classList.add("debug-empty");
ad.innerHTML = `       <div class="ad-title">         <span>! FALLBACK FAKE AD</span>         <button class="x" title="close">X</button>       </div>       <div class="ad-body">         <b>This ad template failed to render, so the archive deployed a backup rectangle with text.</b>         <p><button>acknowledge rectangle</button></p>         <p class="ad-fine">Fallback parody popup.</p>       </div>
    `;
}
}

function spawnAd(manual=false,source=manual ? "manual" : "random"){
  if(popupsAreMuted()){
    if(manual) signalBanner("POPUPS MUTED: quiet signal is active.");
    return;
  }
  if(document.querySelectorAll(".popup-ad").length >= MAX_POPUPS) return;
  const template = adTemplates[Math.floor(Math.random() * adTemplates.length)];
  const ad = document.createElement("div");
  ad.className = `popup-ad ${template.className}`;
  const html = adMarkup(template);
  ad.innerHTML = html;
  verifyPopupMarkup(ad,html,template.className);
  document.body.appendChild(ad);
  positionPopupSafely(ad,template.className);
  ad.querySelector(".x").onclick = () => {
    awardAdClose();
    ad.remove();
  };
  ad.querySelectorAll(".ad-body button").forEach((button)=>{
    button.onclick = () => {
      spawnSticker();
      awardAdTemplateReward(template);
      if(template.className === "ad-aquarium") aquariumEvent();
      if(Math.random() > .72) spawnAd(true,"manual");
    };
  });
  makeDraggable(ad,ad.querySelector(".ad-title"));
  if(source !== "manual"){
    const chaos = getChaosLevel();
    const min = source === "storm" ? 20000 : chaos >= 3 ? 45000 : 35000;
    const max = source === "storm" ? 40000 : chaos >= 3 ? 70000 : 60000;
    setTimeout(()=>{if(ad.isConnected) ad.remove()},min + Math.random() * (max - min));
  }
}

function scheduleNextRandomAd(initial=false){
  clearTimeout(randomAdTimer);
  if(popupsAreMuted()) return;
  const chaos = getChaosLevel();
  const ranges = [[12000,20000],[5000,9000],[4000,7000],[3000,6000],[2000,4000]];
  const [min,max] = initial ? [2000,4000] : ranges[chaos];
  const delay = min + Math.random() * (max - min);
  randomAdTimer = setTimeout(()=>{
    if(!popupsAreMuted() && !adStorm && document.querySelectorAll(".popup-ad").length < MAX_POPUPS) spawnAd(false,"random");
    scheduleNextRandomAd(false);
  },delay);
}

function startRandomAdScheduler(){
  scheduleNextRandomAd(true);
}

function updateAdStormButton(){
  $$("[data-ad-storm]").forEach((button)=>{
    button.textContent = adStorm ? "stop ad storm" : "start ad storm";
    button.setAttribute("aria-pressed",String(adStorm));
  });
  $$("[data-ad-storm-status], #adStormStatus").forEach((status)=>{
    status.textContent = popupsAreMuted() ? "Ad storm: muted by quiet signal." : adStorm ? "Ad storm: BROADCASTING FAST. Close buttons remain legally available." : "Ad storm: paused.";
  });
}

function runAdStorm(){
  clearTimeout(adStormTimer);
  if(popupsAreMuted()){
    adStorm = false;
    updateAdStormButton();
    return;
  }
  if(!adStorm) return;
  const waves = 2 + Math.floor(Math.random() * 2);
  for(let i=0;i<waves;i++){
    if(document.querySelectorAll(".popup-ad").length < MAX_POPUPS) spawnAd(false,"storm");
  }
  adStormTimer = setTimeout(runAdStorm,600 + Math.random() * 800);
}

function toggleAdStorm(){
  if(popupsAreMuted()){
    adStorm = false;
    clearTimeout(adStormTimer);
    updateAdStormButton();
    signalBanner("AD STORM MUTED: quiet signal is active.");
    return;
  }
  adStorm = !adStorm;
  updateAdStormButton();
  if(adStorm){
    unlockAchievement("adStormSurvivor");
    addCurrency("Popup Bucks",3);
    runAdStorm();
  }
  else clearTimeout(adStormTimer);
}

function toggleSpinMode(){
  document.body.classList.toggle("spin-mode");
  updateSpinButtons();
}

function updateSpinButtons(){
  const spinning = document.body.classList.contains("spin-mode");
  $$("[data-spin-toggle]").forEach((button)=>{
    button.textContent = spinning ? "stop spin mode" : "spin mode";
    button.setAttribute("aria-pressed",String(spinning));
  });
}

function makeDraggable(el,handle){
  if(!handle) return;
  let ox = 0;
  let oy = 0;
  let down = false;
  handle.onmousedown = (e) => {
    down = true;
    ox = e.clientX - el.offsetLeft;
    oy = e.clientY - el.offsetTop;
    e.preventDefault();
  };
  addEventListener("mousemove",(e)=>{
    if(!down) return;
    const left = e.clientX - ox;
    const top = e.clientY - oy;
    if(el.classList.contains("popup-ad")) clampPopupPosition(el,left,top,el.className,false);
    else {
      const viewport = getVisualViewportBox();
      const pad = 12;
      el.style.left = Math.max(viewport.offsetLeft + pad,Math.min(viewport.offsetLeft + viewport.width - el.offsetWidth - pad,left)) + "px";
      el.style.top = Math.max(viewport.offsetTop + pad,Math.min(viewport.offsetTop + viewport.height - Math.min(el.offsetHeight,viewport.height - pad * 2) - pad,top)) + "px";
    }
  });
  addEventListener("mouseup",()=>down=false);
}

function bouncingLogo(){
  if($(".bounce-logo")) return;
  const logo = document.createElement("div");
  logo.className = "bounce-logo";
  logo.innerHTML = "<div>VDO<small>ODD SIGNAL</small></div>";
  document.body.appendChild(logo);
  let x = 40 + Math.random() * 120;
  let y = 60 + Math.random() * 120;
  let vx = 2.2;
  let vy = 1.8;
  let hue = 0;
  let activeTrails = 0;
  function spawnVdoTrail(tx,ty,w,h){
    if(document.hidden || activeTrails >= 30) return;
    activeTrails++;
    const trail = document.createElement("div");
    const trailWidth = Math.max(52,Math.round(w * .72));
    const trailHeight = Math.max(28,Math.round(h * .58));
    trail.className = "vdo-trail";
    trail.setAttribute("aria-hidden","true");
    trail.textContent = "VDO";
    trail.style.width = trailWidth + "px";
    trail.style.height = trailHeight + "px";
    trail.style.left = 30 + tx + (w - trailWidth) / 2 + "px";
    trail.style.top = 30 + ty + (h - trailHeight) / 2 + "px";
    document.body.appendChild(trail);
    setTimeout(()=>{
      trail.remove();
      activeTrails = Math.max(0,activeTrails - 1);
    },420);
  }
  function step(){
    const w = logo.offsetWidth;
    const h = logo.offsetHeight;
    const previousX = x;
    const previousY = y;
    const speedBoost = getPurchases()["Slightly Faster VDO"] ? .35 : 0;
    const speed = getChaosMultiplier() + speedBoost;
    x += vx * speed;
    y += vy * speed;
    let hit = false;
    if(x < 0 || x + w > innerWidth){vx *= -1;x = Math.max(0,Math.min(x,innerWidth - w));hit = true}
    if(y < 0 || y + h > innerHeight){vy *= -1;y = Math.max(0,Math.min(y,innerHeight - h));hit = true}
    if(hit){
      hue = (hue + 75) % 360;
      logo.style.filter = `hue-rotate(${hue}deg)`;
      if(Math.random() > .82) spawnSticker();
    }
    logo.style.transform = `translate(${x}px,${y}px)`;
    spawnVdoTrail(previousX,previousY,w,h);
    requestAnimationFrame(step);
  }
  step();
}

function clickGame(){
  const area = $("#clickGame");
  if(!area) return;
  let score = 0;
  const scoreEl = $("#score");
  function make(){
    const t = document.createElement("div");
    t.className = "target";
    t.textContent = ["UFO","BUG","CD","VHS","404","ORB","BOLT"][Math.floor(Math.random() * 7)];
    t.style.left = Math.random() * 78 + "%";
    t.style.top = Math.random() * 75 + "%";
    t.onclick = () => {
      score++;
      scoreEl.textContent = score;
      t.remove();
      make();
      if(score % 5 === 0) spawnAd(false);
    };
    area.appendChild(t);
  }
  make();
}

function bugGame(){
  const area = $("#bugGame");
  if(!area) return;
  let score = 0;
  const out = $("#bugScore");
  function bug(){
    const b = document.createElement("div");
    b.className = "bug";
    b.textContent = ["bug","bit","zap","err"][Math.floor(Math.random() * 4)];
    b.style.left = Math.random() * 82 + "%";
    b.style.top = Math.random() * 80 + "%";
    b.onclick = () => {
      score++;
      out.textContent = score;
      b.remove();
      spawnSticker();
    };
    area.appendChild(b);
    setTimeout(()=>{if(b.isConnected) b.remove()},2600);
  }
  setInterval(bug,650);
}

function startReaction(){
  const box = $("#reactionBox");
  const out = $("#reactionOut");
  if(!box) return;
  reactionReady = false;
  box.className = "reaction-box";
  box.textContent = "wait for signal...";
  out.textContent = "";
  clearTimeout(reactionTimer);
  reactionTimer = setTimeout(()=>{
    reactionReady = true;
    reactionStart = performance.now();
    box.className = "reaction-box go";
    box.textContent = "GO! CLICK!";
  },900 + Math.random() * 2500);
  box.onclick = () => {
    if(!reactionReady){
      box.className = "reaction-box too-soon";
      box.textContent = "TOO SOON";
      out.textContent = "The archive refuses to certify that reflex.";
      clearTimeout(reactionTimer);
    }else{
      const ms = Math.round(performance.now() - reactionStart);
      out.textContent = `${ms} ms. ${ms < 250 ? "Unreasonably fast." : "Acceptable signal capture."}`;
      box.className = "reaction-box";
      box.textContent = "done";
      reactionReady = false;
    }
  };
}

function startPopupMole(){
  const area = $("#popupMole");
  const out = $("#moleScore");
  if(!area) return;
  area.innerHTML = "";
  let score = 0;
  let made = 0;
  const id = setInterval(()=>{
    made++;
    const mole = document.createElement("button");
    mole.className = "mole";
    mole.textContent = ["POP","AD","X","SALE","NOPE"][Math.floor(Math.random() * 5)];
    mole.style.left = Math.random() * 74 + "%";
    mole.style.top = Math.random() * 72 + "%";
    mole.onclick = () => {
      score++;
      out.textContent = score;
      mole.remove();
      spawnSticker();
    };
    area.appendChild(mole);
    setTimeout(()=>{if(mole.isConnected)mole.remove()},900);
    if(made >= 24) clearInterval(id);
  },430);
}

function mysteryButton(){
  const out = $("#mysteryOut");
  const actions = [
    () => {out.textContent = "The button changed its mind.";},
    () => {out.textContent = "A polite fake popup has been notified."; spawnAd(true);},
    () => {out.textContent = "Confetti protocol activated."; spawnConfetti();},
    () => {out.textContent = "The page made a tiny static noise in spirit."; document.body.classList.add("static-burst"); setTimeout(()=>document.body.classList.remove("static-burst"),1800);}
  ];
  actions[Math.floor(Math.random() * actions.length)]();
}

function fakeCaptcha(){
  const out = $("#captchaOut");
  const good = Math.random() > .45;
  out.textContent = good ? "Accepted. The archive believes you are mostly human." : "Rejected. Please select all squares containing existential dread.";
  if(!good){
    playSound("buzz");
    spawnAd(true);
  }
}

function startCornerHunt(){
  const area = $("#cornerHunt");
  const out = $("#cornerOut");
  if(!area) return;
  area.innerHTML = "";
  const dot = document.createElement("button");
  dot.className = "corner-dot";
  dot.title = "click the signal";
  dot.style.left = Math.random() > .5 ? "3px" : "calc(100% - 32px)";
  dot.style.top = Math.random() > .5 ? "3px" : "calc(100% - 32px)";
  dot.onclick = () => {
    out.textContent = "Corner signal captured. It immediately filed a complaint.";
    dot.remove();
    spawnSticker();
  };
  area.appendChild(dot);
  out.textContent = "Find the glowing dot hiding in a corner.";
}

function fortuneClicker(){
  fortuneClicks++;
  const out = $("#fortuneClickOut");
  out.textContent = `Fortune clicks: ${fortuneClicks}. ${randomFortune()}`;
}

function startMemoryGame(){
  const board = $("#memoryBoard");
  const out = $("#memoryOut");
  if(!board) return;
  const symbols = ["CRT","404","AD","VHS","CRT","404","AD","VHS"].sort(()=>Math.random()-.5);
  let first = null;
  let matches = 0;
  board.innerHTML = "";
  symbols.forEach((symbol)=>{
    const tile = document.createElement("button");
    tile.className = "memory-tile";
    tile.dataset.symbol = symbol;
    tile.textContent = "?";
    tile.onclick = () => {
      if(tile.classList.contains("matched") || tile === first) return;
      tile.textContent = symbol;
      if(!first){
        first = tile;
        return;
      }
      if(first.dataset.symbol === symbol){
        tile.classList.add("matched");
        first.classList.add("matched");
        matches++;
        first = null;
        out.textContent = matches === 4 ? "Memory cabinet cleared. The archive reluctantly applauds." : "Match logged.";
        if(matches === 4){
          addInventoryItem("Static Coin",1);
          addCurrency("Static Coins",5);
          spawnConfetti();
        }
      }else{
        const old = first;
        first = null;
        out.textContent = "No match. Static shuffles in the corner.";
        setTimeout(()=>{old.textContent = "?"; tile.textContent = "?"},650);
      }
    };
    board.appendChild(tile);
  });
  out.textContent = "Find the four matching signal pairs.";
}

function buttonRoulette(){
  const out = $("#rouletteOut");
  const results = [
    "Roulette result: one fake popup.",
    "Roulette result: confetti overload.",
    "Roulette result: nothing, but loudly.",
    "Roulette result: secret static wink.",
    "Roulette result: button confidence increased."
  ];
  const roll = Math.floor(Math.random() * results.length);
  if(out) out.textContent = results[roll];
  if(roll === 0) spawnAd(true);
  if(roll === 1) spawnConfetti();
  if(roll === 3) document.body.classList.add("static-burst"), setTimeout(()=>document.body.classList.remove("static-burst"),1400);
}

function hidePixel(){
  const area = $("#hiddenPixelGame");
  const out = $("#pixelOut");
  if(!area) return;
  area.innerHTML = "";
  const p = document.createElement("button");
  p.className = "hidden-pixel";
  p.title = "hidden pixel";
  p.style.left = Math.random() * 92 + "%";
  p.style.top = Math.random() * 82 + "%";
  p.onclick = () => {
    p.remove();
    out.textContent = "Hidden pixel found. It was pretending to be dust.";
    addInventoryItem("Loose Pixel",1);
    unlockAchievement("pixelHunter");
    spawnSticker();
  };
  area.appendChild(p);
  out.textContent = "Find the tiny blinking pixel.";
}

function badPassword(){
  const parts = ["signal","static","crt","mysterybolt","coupon","archive","button","beacon","void"];
  const out = $("#passOut");
  if(out) out.textContent = Array.from({length:4},()=>parts[Math.floor(Math.random()*parts.length)]).join("-") + "-" + Math.floor(Math.random()*9999);
}

function randomFortune(){
  const f = [
    "A blinking object will offer advice.",
    "The archive hums at a frequency only old modems respect.",
    "A fake coupon will arrive exactly too late.",
    "A tiny cabinet wants one more imaginary quarter.",
    "The mystery bolt knows where the missing panel went."
  ];
  return f[Math.floor(Math.random() * f.length)];
}

function fortune(){
  const out = $("#fortuneOut");
  if(out) out.textContent = randomFortune();
}

function guestbook(){
  const form = $("#guestForm");
  const list = $("#guestList");
  const clear = $("#clearGuestbook");
  if(!form || !list) return;
  let saved = JSON.parse(localStorage.getItem("oddGuestbook") || "[]");
  const render = () => {
    list.innerHTML = saved.map((x)=>`<div class="box"><b>${clean(x.name)}</b> tuned in:<br>${clean(x.msg)}<p class="hidden-note">${clean(x.date)}</p></div>`).join("") || "<div class='box'><i>No entries yet. The page is listening.</i></div>";
  };
  form.onsubmit = (e) => {
    e.preventDefault();
    saved.unshift({
      name:$("#gname").value || "Anonymous Signal",
      msg:$("#gmsg").value || "The archive blinked back.",
      date:new Date().toLocaleString()
    });
    saved = saved.slice(0,30);
    localStorage.setItem("oddGuestbook",JSON.stringify(saved));
    render();
    form.reset();
  };
  if(clear){
    clear.onclick = () => {
      if(confirm("Clear the local guestbook entries in this browser?")){
        saved = [];
        localStorage.setItem("oddGuestbook","[]");
        render();
      }
    };
  }
  render();
}

function fakeDownload(name){
  const out = $("#downloadOut");
  if(out) out.innerHTML = `<b>${clean(name)}</b> failed successfully. No file was created, but the fake progress bar feels seen.`;
  spawnAd(true);
}

function randomThing(){
  const a = ["haunted","overclocked","discount","ancient","forbidden","glowing","sideways","unlabeled"];
  const b = ["keyboard","CRT","floppy disk","coupon","garden hose","router","antenna","receipt","tiny ladder"];
  const out = $("#thingOut");
  if(out) out.textContent = "Cataloged object: " + a[Math.floor(Math.random()*a.length)] + " " + b[Math.floor(Math.random()*b.length)];
}

function fakeFact(){
  const facts = [
    "Every abandoned button contains one unspent click.",
    "A web ring rotates counterclockwise when nobody is watching.",
    "CRT static can season a loading bar if applied incorrectly.",
    "The archive once cataloged a folder named New Folder (final) (real).",
    "A guestbook entry travels exactly one browser deep."
  ];
  const out = $("#factOut");
  if(out) out.textContent = facts[Math.floor(Math.random() * facts.length)];
}

function cursedLoad(){
  const bar = $("#loadBar span");
  const out = $("#loadOut");
  if(!bar) return;
  let n = 0;
  clearInterval(window.cursedLoader);
  window.cursedLoader = setInterval(()=>{
    n += Math.random() * 18;
    if(n > 99 && Math.random() > .35) n = 13;
    bar.style.width = Math.min(100,n) + "%";
    out.textContent = n >= 100 ? "Loading completed and immediately forgot why." : "Loading: " + Math.floor(n) + "%";
    if(n >= 100) clearInterval(window.cursedLoader);
  },240);
}

function uselessButton(btn){
  const labels = ["still useless","no output","button confidence +1","clicked, technically","try again?","archive says thanks"];
  btn.textContent = labels[Math.floor(Math.random() * labels.length)];
  if(Math.random() > .7) spawnSticker();
}

function fakeSurvey(){
  const out = $("#surveyOut");
  if(out) out.textContent = "Survey processed. Result: the archive recommends more blinking, somehow.";
}

function boltOracle(){
  const msg = [
    "That bolt belongs to a door that only appears during loading screens.",
    "Keep it. The archive will ask for it later.",
    "It is load-bearing in a symbolic way.",
    "The bolt says: turn left at the fake banner.",
    "Do not tighten the prophecy past 12 nonsense-units."
  ];
  const out = $("#boltOut");
  if(out) out.textContent = msg[Math.floor(Math.random() * msg.length)];
}

function archiveExperiment(){
  const ideas = [
    "A clock that only reports expired coupon times.",
    "A shrine for unclaimed desktop shortcuts.",
    "A loading bar that gets nervous near 100%.",
    "A fake banner that reviews other fake banners.",
    "A tiny maze where every exit leads to another button."
  ];
  const out = $("#ideaOut");
  if(out) out.textContent = ideas[Math.floor(Math.random() * ideas.length)];
}

function signalName(){
  const first = ["Dust","Neon","Static","Blink","Socket","Vapor","Click","Ribbon"];
  const last = ["Beacon","Widget","Oracle","Button","Signal","Panel","Cabinet"];
  const out = $("#signalOut");
  if(out) out.textContent = first[Math.floor(Math.random()*first.length)] + " " + last[Math.floor(Math.random()*last.length)];
}

function lightPanel(){
  const p = $("#lightPanel");
  if(!p) return;
  p.innerHTML = "";
  for(let i=0;i<24;i++){
    const l = document.createElement("button");
    l.className = "light";
    l.title = "toggle archive light";
    l.onclick = () => l.classList.toggle("on");
    p.appendChild(l);
  }
}

function scrambleMeters(){
  $$(".nonsense-meter span").forEach((span)=>span.style.width = Math.floor(8 + Math.random() * 92) + "%");
  const out = $("#meterOut");
  if(out) out.textContent = "Meters recalibrated without permission.";
}

function generateWarning(){
  const warnings = [
    "Warning: specimen is blinking in alphabetical order.",
    "Warning: coupon pressure exceeds recommended nonsense limits.",
    "Warning: fake science panel has achieved confidence.",
    "Warning: loading void leaked into the snack drawer.",
    "Warning: static density is now crunchy."
  ];
  const out = $("#warningOut");
  if(out) out.textContent = warnings[Math.floor(Math.random() * warnings.length)];
}

function toggleContainment(){
  const out = $("#containmentOut");
  document.body.classList.toggle("containment-mode");
  if(out) out.textContent = document.body.classList.contains("containment-mode") ? "Containment tape deployed around the vibes." : "Containment tape removed. Good luck.";
}

function recalibrateBeacon(){
  const out = $("#beaconOut");
  if(out) out.textContent = ["Beacon points north-ish.","Beacon points toward the fake ad museum.","Beacon refuses cardinal directions.","Beacon now tracks suspicious buttons."][Math.floor(Math.random()*4)];
  spawnSticker();
}

function flipPanel(){
  document.body.classList.toggle("nightmare");
  const out = $("#labOut");
  if(out) out.textContent = document.body.classList.contains("nightmare") ? "Spectrum inversion active." : "Spectrum inversion parked.";
}

function focusFakeWindow(w){
  fakeWindowTop++;
  w.style.zIndex = fakeWindowTop;
  $$(".taskbar-window").forEach((button)=>button.classList.remove("active"));
  const task = document.querySelector(`[data-window-button="${w.dataset.windowId}"]`);
  if(task) task.classList.add("active");
}

function addTaskbarButton(w,title){
  const bar = $("#taskbarButtons");
  if(!bar) return null;
  const button = document.createElement("button");
  button.className = "taskbar-window active";
  button.dataset.windowButton = w.dataset.windowId;
  button.textContent = title;
  button.onclick = () => {
    w.style.display = "block";
    focusFakeWindow(w);
  };
  bar.appendChild(button);
  return button;
}

function openFakeWindow(title,body){
  const w = document.createElement("div");
  w.className = "fake-window";
  w.dataset.windowId = "fake-window-" + (++fakeWindowCount);
  w.style.left = Math.max(10,Math.random() * Math.max(20,innerWidth - 390)) + "px";
  w.style.top = Math.max(10,Math.random() * Math.max(20,innerHeight - 245)) + "px";
  w.innerHTML = `<div class="win-title"><span>${clean(title)}</span><button class="x">X</button></div><div class="win-body"><p>${clean(body)}</p><button class="win-ok">OK</button><button class="win-help">fake help</button></div>`;
  document.body.appendChild(w);
  const taskButton = addTaskbarButton(w,title);
  const closeWindow = () => {
    if(taskButton) taskButton.remove();
    w.remove();
  };
  w.querySelector(".x").onclick = closeWindow;
  w.querySelector(".win-ok").onclick = closeWindow;
  w.querySelector(".win-help").onclick = () => spawnAd(true);
  w.onmousedown = () => focusFakeWindow(w);
  makeDraggable(w,w.querySelector(".win-title"));
  focusFakeWindow(w);
}

function desktopClock(){
  const el = $("#clockBox");
  if(!el) return;
  const tick = () => el.textContent = new Date().toLocaleTimeString();
  tick();
  setInterval(tick,1000);
}

function desktopAlert(){
  openFakeWindow("Archive Alert","A fake desktop window noticed another fake desktop window. The recursion has been documented.");
}

function addFish(){
  const tank = $("#aquarium");
  if(!tank) return;
  const creatures = [
    {type:"fish", symbol:"><(((o>"},
    {type:"fish", symbol:"><>"},
    {type:"eel", symbol:"~==~~"},
    {type:"crab", symbol:"(V)V"},
    {type:"boot", symbol:"L__"},
    {type:"sub", symbol:"<|=|>"},
    {type:"bubble-creature", symbol:"(o)"}
  ];
  const creature = creatures[Math.floor(Math.random() * creatures.length)];
  const f = document.createElement("div");
  f.className = `fish creature creature-${creature.type}`;
  f.textContent = creature.symbol;
  f.style.top = 18 + Math.random() * 245 + "px";
  f.style.animationDuration = 7 + Math.random() * 12 + "s";
  f.style.animationDelay = -(Math.random() * 6) + "s";
  f.onclick = () => {
    const out = $("#fishOut");
    if(out) out.textContent = `The ${creature.type.replace("-"," ")} filed a tiny incident report.`;
    addInventoryItem(creature.type === "crab" ? "Desktop Crab Shell" : "Aquarium Bubble",1);
    makeBubble(tank,parseFloat(f.style.top) || 120);
  };
  tank.appendChild(f);
}

function makeBubble(tank,y=260){
  const b = document.createElement("div");
  b.className = "bubble";
  const size = 8 + Math.random() * 20;
  b.style.width = size + "px";
  b.style.height = size + "px";
  b.style.left = Math.random() * 92 + "%";
  b.style.top = y + "px";
  tank.appendChild(b);
  setTimeout(()=>b.remove(),4200);
}

function feedFish(){
  const out = $("#fishOut");
  if(out) out.textContent = "The aquarium accepts the browser crumbs and becomes slightly weirder.";
  addInventoryItem("Aquarium Bubble",1);
  addCurrency("Coupon Dust",1);
  unlockAchievement("aquariumGoblin");
  addQuestClue("aquarium","bubble points toward coupon");
  for(let i=0;i<4;i++) addFish();
}

function aquariumEvent(){
  const tank = $("#aquarium");
  const out = $("#fishOut");
  if(!tank) return;
  for(let i=0;i<12;i++) makeBubble(tank,260 + Math.random() * 30);
  if(out) out.textContent = ["Bubble storm declared.","A sign floats by: DO NOT TAP GLASS.","The boot moved two pixels."][Math.floor(Math.random()*3)];
}

function aquarium(){
  const tank = $("#aquarium");
  if(!tank) return;
  for(let i=0;i<10;i++) addFish();
  tank.onclick = (e) => {
    if(e.target === tank) makeBubble(tank,e.offsetY);
  };
}

function randomSecret(){
  return [
    "The corner hit will happen when attention drifts.",
    "Somewhere, a forgotten toolbar still updates its feelings.",
    "A mystery cable becomes useful once every seven years.",
    "The fake ad is afraid of the close button.",
    "The deep archive has a door labeled NO NORMAL PAGES."
  ][Math.floor(Math.random()*5)];
}

function unlockSecret(){
  const input = $("#secretPassword");
  const out = $("#secretGateOut");
  const panel = $("#secretPanel");
  if(!input || !panel) return;
  if(input.value.trim().toLowerCase() === "signal404"){
    panel.classList.add("unlocked");
    out.textContent = "ACCESS GRANTED: deep archive door unstuck.";
    unlockAchievement("secretDoor");
    addQuestClue("secret","bolt waits beside coupon and vhs");
    addInventoryItem("404 Shard",1);
    playSound("secret");
    spawnConfetti();
  }else{
    out.textContent = "ACCESS DENIED: the archive heard static.";
    playSound("buzz");
    spawnAd(true);
  }
}

function secretRitual(){
  secretRitualCount++;
  const out = $("#ritualOut");
  const steps = [
    "Ritual step 1: tap the invisible banner.",
    "Ritual step 2: sort the forbidden files by smell.",
    "Ritual step 3: ask the loading bar for forgiveness.",
    "Ritual complete: the archive emits one respectful beep."
  ];
  if(out) out.textContent = steps[Math.min(secretRitualCount - 1, steps.length - 1)];
  addCurrency("Static Coins",1);
  if(secretRitualCount % 4 === 0){
    addInventoryItem("VDO Spark",1);
    spawnConfetti();
  }
}

function makeNoiseText(btn){
  btn.textContent = ["BEEP","BOOP","BZZT","STATIC","NOPE"][Math.floor(Math.random()*5)];
  spawnSticker();
}

function randomWebringJump(){
  const pages = ["void.html","ads.html","oracle.html","objects.html","tv.html","buttons.html","maze.html","random.html","aquarium.html"];
  location.href = pages[Math.floor(Math.random() * pages.length)];
}

function randomObjectShrine(){
  const out = $("#shrineOut");
  const objects = ["unlabeled adapter","green plastic jewel","ticket from nowhere","tiny brass switch","folded map to a 404","receipt for moon gas","single perfect pixel"];
  if(out) out.textContent = objects[Math.floor(Math.random() * objects.length)];
}

function tvStatic(){
  const out = $("#tvOut");
  if(out) out.textContent = ["CHANNEL 03: lost cooking show for cables","CHANNEL 17: weather inside a floppy disk","CHANNEL 44: silent auction for fake banners","CHANNEL 99: the loading void waves back"][Math.floor(Math.random()*4)];
  document.body.classList.add("static-burst");
  setTimeout(()=>document.body.classList.remove("static-burst"),1800);
}

function voidMessage(){
  const out = $("#voidOut");
  if(out) out.textContent = ["Still loading.","Still loading..","Still loading...","It loaded, but only emotionally.","The void requests another second."][Math.floor(Math.random()*5)];
}

function mazeChoice(id){
  const out = $("#mazeOut");
  const text = {
    a:"Room A contains a button labeled OTHER BUTTON.",
    b:"Room B smells like warm plastic and unresolved links.",
    c:"Room C loops back to itself with confidence.",
    d:"Room D opens a fake popup because of course it does.",
    e:"Room E has a sign: the exit is a mood.",
    f:"Room F reveals a shortcut to the oracle."
  };
  if(out) out.textContent = text[id] || "The maze blinks.";
  if(id === "d") spawnAd(true);
}

function renderInventory(){
  const grid = $("#inventoryGrid");
  if(!grid) return;
  const inv = getInventory();
  grid.innerHTML = Object.entries(inventoryCatalog).map(([name,meta])=>{
    const count = Number(inv[name] || 0);
    return `<div class="inventory-card ${count ? "owned" : ""}"><h3>${clean(name)}</h3><p>${clean(meta.desc)}</p><b>Rarity: ${clean(meta.rarity)}</b><p>Count: ${count}</p></div>`;
  }).join("");
}

function renderAchievements(){
  const grid = $("#achievementGrid");
  if(!grid) return;
  const achievements = getAchievements();
  grid.innerHTML = Object.entries(achievementCatalog).map(([id,a])=>{
    const unlocked = achievements[id];
    return `<div class="achievement-card ${unlocked ? "unlocked" : ""}"><h3>${clean(a.name)}</h3><p>${clean(a.desc)}</p><b>${unlocked ? "Unlocked" : "Locked"}</b>${unlocked ? `<p>${clean(unlocked.date)}</p>` : ""}</div>`;
  }).join("");
}

const fileFolders = {
  "/DO_NOT_OPEN":["panic_receipt.txt","green_fish_warning.txt","bolt_coupon_vhs.clue"],
  "/old_buttons":["beep_button.btn","button_confidence.ini","under_construction.gif.txt"],
  "/coupons":["zero_percent.cpn","coupon_ash.dat","laminator_receipt.fake"],
  "/secret_static":["signal404_note.txt","ch404_recording.wav.txt","static_sample.jar"],
  "/images_that_loaded_wrong":["vdo_corner.bmp","fish_but_sideways.png.txt","banner_fossil.jpg.txt"],
  "/system32_but_fake":["do_not_delete_fake.dll","toolbar_worm.sys.txt","nothing_driver.ini"],
  "/desktop_pet_records":["crab_shell.log","tiny_modem_sighting.txt","coupon_bug_tracks.dat"],
  "/radio_logs":["fm404_transcript.txt","aquarium_weather.log","banner_jazz.playlist"]
};

function renderFileExplorer(){
  const folders = $("#fileFolders");
  if(!folders) return;
  folders.innerHTML = Object.keys(fileFolders).map((folder)=>`<button onclick="showFakeFolder('${folder}')">${folder}</button>`).join("");
  showFakeFolder("/DO_NOT_OPEN");
}

function showFakeFolder(folder){
  const files = $("#fileList");
  const title = $("#folderTitle");
  if(title) title.textContent = folder;
  if(!files) return;
  files.innerHTML = (fileFolders[folder] || []).map((file)=>`<button onclick="openFakeFile('${folder}','${file}')">${file}</button>`).join("");
}

function openFakeFile(folder,file){
  const text = {
    "bolt_coupon_vhs.clue":"ARG clue fragment: bolt-coupon-vhs. This is theatrical, not authentication.",
    "green_fish_warning.txt":"Do not click the green fish unless the bubble asks nicely.",
    "signal404_note.txt":"The first door answers to signal404. The second door likes bolt, coupon, and vhs.",
    "fm404_transcript.txt":"CH 404 repeats: static is a place, not a problem."
  }[file] || `Opened ${file} from ${folder}. Contents: corrupted but charming.`;
  openFakeWindow(file,text);
  addInventoryItem(file.includes("coupon") ? "Cursed Coupon" : file.includes("static") ? "Radio Static Sample" : "Fake Patch Note",1);
  const opened = incrementStat("oddFilesOpened",1);
  if(opened >= 10) unlockAchievement("fileGoblin");
  if(file.includes("clue")) addQuestClue("files","bolt-coupon-vhs");
}

const searchFragments = [
  "was last seen inside a banner ad","is legally distinct from a real toolbar","requires three coupons and a patient modem","fell into the loading void","became a desktop shortcut with regrets","is stored next to the 404 shard","won an award for excessive borders","smells like warm CRT plastic","was rejected by the fake update installer","contains one heroic table cell",
  "opened a popup and apologized","made the aquarium slightly suspicious","is classified as premium dust","has a weather advisory","was laminated for safety","lost a fight with a progress bar","was indexed by a tired web ring","contains 12 new bugs","became a patch note","is available in Static City",
  "was translated into modem beeps","knows the panic button personally","filed a complaint with ArchiveBot 98","is hidden in /DO_NOT_OPEN","tuned itself to FM 40.4","was eaten by a coupon bug","caused a fake system alert","is mostly decorative","requires localStorage to remember anything","appears during dial-up apocalypse",
  "was printed on newspaper coupon paper","has a tiny VDO spark inside","was last cached in 2004","cannot be downloaded because it is fictional","belongs in the object shrine","is now a shop upgrade","was found under a fake taskbar","contains the phrase bolt-coupon-vhs","was foggy with mild popups","is waiting in the Tiny Link Maze",
  "was certified by Table Layout Council","contains 0% real malware","is parody-only and proud","fell from the top of the browser","was counted by a fake visitor counter","opened a draggable window","made a button more confident","has suspicious toolbar humidity","is a browser-game fossil","started blinking in self defense"
];

function cursedSearch(){
  const input = $("#searchInput");
  const results = $("#searchResults");
  if(!input || !results) return;
  const q = input.value.trim() || "blank query";
  const lower = q.toLowerCase();
  const eggs = {
    bolt:"The bolt result whispers: coupon comes before vhs.",
    coupon:"Coupon result: save 0% and collect Coupon Dust.",
    vdo:"VDO result: keep watching the corner bounce.",
    aquarium:"Aquarium result: bubbles are evidence.",
    signal404:"signal404 opens the first harmless secret gate.",
    panic:"Panic result: one emergency popup always remains.",
    popup:"Popup result: close enough ads and the archive pays you.",
    static:"Static result: tune CH 404 for the second clue.",
    archive:"Archive result: the toybox has no bottom."
  };
  if(eggs[lower]){
    addQuestClue("search",eggs[lower]);
    addInventoryItem("404 Shard",1);
  }
  const rows = Array.from({length:7},(_,i)=>{
    const fragment = searchFragments[Math.floor(Math.random()*searchFragments.length)];
    return `<div class="search-result"><h3>${clean(q)} result ${i+1}</h3><p>${clean(q)} ${clean(fragment)}.</p><a onclick="spawnAd(true)">cached copy</a></div>`;
  });
  if(eggs[lower]) rows.unshift(`<div class="search-result special"><h3>Special result</h3><p>${clean(eggs[lower])}</p></div>`);
  results.innerHTML = rows.join("");
}

function generateLostPage(){
  const out = $("#lostOutput");
  if(!out) return;
  const titles = ["Coupon Cathedral","Static Arcade Wing","Lost Toolbar Chapel","VDO Bounce Shrine","Aquarium Afterhours","Popup Museum Basement","Button Orchard"];
  const warnings = ["do not trust the third button","page may contain theatrical dust","loading bar is decorative","coupon winds increasing","normal layout not found"];
  const lore = ["A banner ad learned to dream in tables.","The fake visitor counter counted backward once.","A folder named maybe opened itself.","Someone replaced calm mode with suspicious calm mode.","The aquarium left a wet CSS footprint."];
  const urls = ["/void?signal=73","/lost/page/CRT-404","/archive/cache/coupon-void","/popup/museum/wing-7","/radio/ch404/static-loop"];
  const item = Math.random() > .55 ? awardRandomJunk("event") : "";
  if(Math.random() > .65) addQuestClue("lost","vhs follows coupon in the deeper phrase");
  out.innerHTML = `<div class="lost-panel" style="background:hsl(${Math.random()*360},70%,16%)"><p class="fake-url">${urls[Math.floor(Math.random()*urls.length)]}</p><h2>${titles[Math.floor(Math.random()*titles.length)]}</h2><p><b>Warning:</b> ${warnings[Math.floor(Math.random()*warnings.length)]}</p><p>${lore[Math.floor(Math.random()*lore.length)]}</p><button onclick="spawnAd(true)">lost fake ad</button><button onclick="buttonRoulette()">page button</button>${item ? `<p>Collected: ${clean(item)}</p>` : ""}</div>`;
}

function askArchiveBot(topic){
  const out = $("#botOutput");
  if(!out) return;
  const replies = {
    bolt:["The bolt is not missing. Reality is missing the hole.","Ask again after collecting coupon dust."],
    ads:["Ads exist because buttons became lonely.","Every popup is fake, but the border is sincere."],
    link:["Forbidden link points to /DO_NOT_OPEN, obviously.","Try the search engine with signal404."],
    aquarium:["The aquarium is mostly CSS and suspicious bubbles.","Do not negotiate with the boot."],
    prophecy:["A loading bar will betray you at 99%.","The second phrase contains bolt, coupon, and vhs."],
    vdo:["The VDO signal is legally distinct and spiritually round.","Watch long enough and it leaves sparks."],
    panic:["Panic is a button, not a plan.","The emergency popup is required by archive law."]
  };
  const list = replies[topic] || replies.prophecy;
  out.innerHTML += `<p><b>ArchiveBot 98:</b> ${clean(list[Math.floor(Math.random()*list.length)])}</p>`;
}

let archiveRadioAudio = null;
let currentRadioStation = "";

// Put owned or royalty-free MP3/OGG/WAV files in assets/audio, or replace src values with direct HTTPS stream URLs.
const radioStations = {
  "FM 40.4":{name:"Banner Ad Jazz",now:"saxophone over a blinking coupon",item:"Radio Static Sample",src:"../assets/audio/banner-jazz.wav",type:"audio/wav"},
  "FM 98.6":{name:"Aquarium Weather",now:"humid bubbles over soft modem rain",item:"Weather Pixel",src:"../assets/audio/aquarium-weather.wav",type:"audio/wav"},
  "AM 666":{name:"Loading Bar Sermons",now:"99 percent forever and amen",item:"Broken Loading Bar",src:"../assets/audio/loading-sermon.wav",type:"audio/wav"},
  "FM 13.7":{name:"Coupon Emergency Broadcast",now:"urgent savings with no value",item:"Coupon Dust",src:"../assets/audio/coupon-emergency.wav",type:"audio/wav"},
  "CH 404":{name:"Lost Signal",now:"static clue: bolt-coupon-vhs",item:"Radio Static Sample",src:"../assets/audio/ch404-static.wav",type:"audio/wav"},
  "FM 88.8":{name:"VDO Corner Bounce Watch",now:"live commentary on a near miss",item:"VDO Spark",src:"../assets/audio/vdo-corner.wav",type:"audio/wav"}
};

function getArchiveRadioAudio(){
  if(!archiveRadioAudio){
    archiveRadioAudio = new Audio();
    archiveRadioAudio.preload = "none";
    archiveRadioAudio.loop = true;
    archiveRadioAudio.volume = Number(localStorage.getItem("oddRadioVolume") || .65);
    archiveRadioAudio.addEventListener("error",()=>{
      if(currentRadioStation) renderRadioOutput(currentRadioStation,"Playback blocked or stream unavailable. Try another station.");
    });
  }
  return archiveRadioAudio;
}

function renderRadioOutput(station,status){
  const data = radioStations[station];
  const out = $("#radioOutput");
  if(!out || !data) return;
  const volume = Math.round(getArchiveRadioAudio().volume * 100);
  const sourceText = data.src ? "Playing real archive audio" : "No real signal attached yet.";
  out.innerHTML = `<div class="radio-player"><h2>${clean(station)} - ${clean(data.name)}</h2><p class="radio-now"><b>Now playing:</b> ${clean(data.now)}</p><p class="radio-status">${clean(status || sourceText)}</p><div class="radio-controls"><button onclick="radioPlay()">play</button><button onclick="radioPause()">pause</button><button onclick="radioStop()">stop</button><label>volume <input type="range" min="0" max="1" step="0.05" value="${getArchiveRadioAudio().volume}" oninput="setRadioVolume(this.value)"></label><span data-radio-volume-value>${volume}%</span></div><p class="mini-status">${data.src ? `Signal source: ${clean(data.src)}` : "Static-only station. Awaiting a real file or stream."}</p></div>`;
}

function radioPlay(){
  const data = radioStations[currentRadioStation];
  if(!data) return;
  const audio = getArchiveRadioAudio();
  if(!data.src){
    renderRadioOutput(currentRadioStation,"No real signal attached yet.");
    return;
  }
  if(!audio.src) audio.src = new URL(data.src,window.location.href).href;
  audio.dataset.type = data.type || "";
  audio.play()
    .then(()=>renderRadioOutput(currentRadioStation,"Playing real archive audio."))
    .catch(()=>renderRadioOutput(currentRadioStation,"Playback blocked or stream unavailable. Try another station."));
}

function radioPause(){
  const audio = getArchiveRadioAudio();
  audio.pause();
  if(currentRadioStation) renderRadioOutput(currentRadioStation,"Paused in the static.");
}

function radioStop(){
  const audio = getArchiveRadioAudio();
  audio.pause();
  try{audio.currentTime = 0}catch(e){}
  if(currentRadioStation) renderRadioOutput(currentRadioStation,"Stopped. The antenna is sulking.");
}

function setRadioVolume(value){
  const audio = getArchiveRadioAudio();
  const volume = Math.max(0,Math.min(1,Number(value)));
  audio.volume = volume;
  localStorage.setItem("oddRadioVolume",String(volume));
  $$("[data-radio-volume-value]").forEach((el)=>el.textContent = `${Math.round(volume * 100)}%`);
}

function tuneRadio(station){
  const data = radioStations[station];
  if(!data) return;
  currentRadioStation = station;
  const audio = getArchiveRadioAudio();
  renderRadioOutput(station,data.src ? "Waking real archive audio..." : "No real signal attached yet.");
  document.body.dataset.radioVibe = station.replace(/\W/g,"");
  addInventoryItem(data.item,1);
  addCurrency("Static Coins",2);
  const n = incrementStat("oddRadioTunes",1);
  if(station === "CH 404") addQuestClue("radio","CH 404 repeats bolt-coupon-vhs");
  if(n >= 5) unlockAchievement("radioDrifter");
  playSound("blip");
  if(data.src){
    audio.pause();
    audio.src = new URL(data.src,window.location.href).href;
    audio.dataset.type = data.type || "";
    audio.load();
    audio.play()
      .then(()=>renderRadioOutput(station,"Playing real archive audio."))
      .catch(()=>renderRadioOutput(station,"Playback blocked or stream unavailable. Try another station."));
  }
  else {
    audio.pause();
    audio.removeAttribute("src");
    audio.load();
  }
}

const weatherPlaces = ["Static City","Toolbar Swamp","Loading Void","Coupon Desert","Aquarium District","Desktop Plains","Popup Valley","VDO Ridge"];
const weatherForecasts = ["raining pixels","40% chance of coupon","foggy with mild popups","high static pressure","banner winds from the east","suspiciously humid toolbar conditions","loading void advisory","warm with scattered fake alerts"];

function refreshWeather(){
  const place = $("#weatherPlace");
  const out = $("#weatherOutput");
  const location = place ? place.value : weatherPlaces[Math.floor(Math.random()*weatherPlaces.length)];
  const forecast = weatherForecasts[Math.floor(Math.random()*weatherForecasts.length)];
  if(out) out.innerHTML = `<h2>${clean(location)}</h2><p>${clean(forecast)}</p><p>Pressure: ${Math.floor(404+Math.random()*300)} static units.</p>`;
  addInventoryItem("Weather Pixel",1);
  addCurrency("Coupon Dust",1);
  const n = incrementStat("oddWeatherRefreshes",1);
  if(n >= 5) unlockAchievement("weatherLiar");
}

const patchNotes = ["Added 12 new bugs","Removed stability","Improved button confidence","Increased popup humidity","Fixed one issue by creating three smaller issues","Replaced calm mode with suspicious calm mode","Added premium dust support"];

function viewPatchNotes(){
  const out = $("#updateOutput");
  if(out) out.innerHTML = `<ul>${patchNotes.map((note)=>`<li>${clean(note)}</li>`).join("")}</ul>`;
}

function installFakeUpdate(){
  const bar = $("#updateBar span");
  const out = $("#updateOutput");
  if(!bar || !out) return;
  let n = 0;
  clearInterval(window.fakeUpdateTimer);
  window.fakeUpdateTimer = setInterval(()=>{
    n += 8 + Math.random()*16;
    if(n >= 99){
      n = 99;
      bar.style.width = "99%";
      out.textContent = "Update failed at 99%. This is considered a feature.";
      addInventoryItem("Fake Patch Note",1);
      addCurrency("Static Coins",10);
      unlockAchievement("patchSurvivor");
      clearInterval(window.fakeUpdateTimer);
      return;
    }
    bar.style.width = n + "%";
    out.textContent = "Installing suspicious calm mode: " + Math.floor(n) + "%";
  },240);
}

function rollbackFakeUpdate(){
  const out = $("#updateOutput");
  if(out) out.textContent = "Rollback complete. Version is worse but more honest.";
  addInventoryItem("Broken Loading Bar",1);
}

const shopItems = {
  "Louder Beep License":{cost:["Static Coins",8],desc:"Beep confidence officially increased."},
  "Slightly Faster VDO":{cost:["Popup Bucks",10],desc:"The bouncing logo gets a tiny safe speed bump."},
  "Premium Dust":{cost:["Coupon Dust",6],desc:"Dust, but it knows HTML."},
  "Ad Storm Insurance":{cost:["Popup Bucks",12],desc:"No coverage, only a badge of poor judgment."},
  "Mystery Bolt Polish":{cost:["Static Coins",5],desc:"Makes one bolt slightly shinier."},
  "Aquarium Breadcrumbs":{cost:["Coupon Dust",5],desc:"Fish-like symbols appreciate this."},
  "Invisible Cursor Coupon":{cost:["Popup Bucks",7],desc:"Cannot be seen, cannot be redeemed."},
  "Coupon Laminator":{cost:["Coupon Dust",12],desc:"Preserves fake savings forever."},
  "Emergency Popup Helmet":{cost:["Static Coins",14],desc:"The helmet is also a popup."}
};

function renderShop(){
  const grid = $("#shopGrid");
  if(!grid) return;
  const purchases = getPurchases();
  grid.innerHTML = Object.entries(shopItems).map(([name,item])=>{
    const [type,cost] = item.cost;
    return `<div class="shop-card ${purchases[name] ? "owned" : ""}"><h3>${clean(name)}</h3><p>${clean(item.desc)}</p><p>Cost: ${cost} ${clean(type)}</p><button onclick="buyShopItem('${name}')">${purchases[name] ? "owned" : "buy fake item"}</button></div>`;
  }).join("");
  setStatusText("[data-shop-currency]",currencySummary());
}

function buyShopItem(name){
  const item = shopItems[name];
  if(!item) return;
  const purchases = getPurchases();
  if(purchases[name]) return;
  const [type,cost] = item.cost;
  const currency = getCurrency();
  if(Number(currency[type] || 0) < cost){
    const out = $("#shopOut");
    if(out) out.textContent = "Not enough fake money. Go bother the archive more.";
    playSound("buzz");
    return;
  }
  currency[type] -= cost;
  writeJSON("oddCurrency",currency);
  purchases[name] = {date:new Date().toLocaleString()};
  writeJSON("oddShopPurchases",purchases);
  addInventoryItem(name,1);
  unlockAchievement("shopVictim");
  renderShop();
  updateArchiveDashboard();
}

const spiritEntries = [
  "Visitor from 2004: this site broke my toolbar, 10/10",
  "Unknown: do not click the green fish",
  "Guest_404: I left my cursor here in 2007",
  "DialupKid: page loaded after only 7 minutes, impressive",
  "BannerFan: the coupon is lying again",
  "StaticPal: CH 404 said something about vhs"
];

function summonSpiritEntry(){
  const list = $("#spiritEntries");
  if(!list) return;
  const entry = spiritEntries[Math.floor(Math.random()*spiritEntries.length)];
  const div = document.createElement("div");
  div.className = "box spirit-entry";
  div.textContent = entry;
  list.prepend(div);
  addInventoryItem("Haunted Floppy",1);
}

addEventListener("DOMContentLoaded",()=>{
  visitorCounter();
  randomQuote();
  clickGame();
  bugGame();
  guestbook();
  lightPanel();
  desktopClock();
  aquarium();
  bouncingLogo();
  ensureExpandedNav();
  enhanceSiteControls();
  addSoundToggle();
  attachGlobalClickEffects();
  updateAdStormButton();
  updateSpinButtons();
  updateChaosControls();
  updateArchiveDashboard();
  renderInventory();
  renderAchievements();
  renderFileExplorer();
  renderQuestClues();
  renderShop();
  startRandomAdScheduler();
  startRandomEventEngine();
  setTimeout(()=>unlockAchievement("vdoWitness"),45000);

  window.addInventoryItem = addInventoryItem;
  window.unlockAchievement = unlockAchievement;
  window.addCurrency = addCurrency;
  window.setChaosLevel = setChaosLevel;
  window.triggerRandomEvent = triggerRandomEvent;
  window.panicButton = panicButton;
  window.spawnDesktopPet = spawnDesktopPet;
  window.unlockDeeperArchive = unlockDeeperArchive;
  window.spawnConfetti = spawnConfetti;
  window.clickPuff = clickPuff;
  window.playSound = playSound;
  window.toggleSound = toggleSound;
  window.fortune = fortune;
  window.spawnAd = spawnAd;
  window.toggleAdStorm = toggleAdStorm;
  window.togglePopupMute = togglePopupMute;
  window.startRandomAdScheduler = startRandomAdScheduler;
  window.toggleSpinMode = toggleSpinMode;
  window.spawnSticker = spawnSticker;
  window.fakeDownload = fakeDownload;
  window.randomThing = randomThing;
  window.fakeFact = fakeFact;
  window.cursedLoad = cursedLoad;
  window.uselessButton = uselessButton;
  window.fakeSurvey = fakeSurvey;
  window.boltOracle = boltOracle;
  window.archiveExperiment = archiveExperiment;
  window.signalName = signalName;
  window.openFakeWindow = openFakeWindow;
  window.desktopAlert = desktopAlert;
  window.startReaction = startReaction;
  window.startPopupMole = startPopupMole;
  window.mysteryButton = mysteryButton;
  window.fakeCaptcha = fakeCaptcha;
  window.startCornerHunt = startCornerHunt;
  window.fortuneClicker = fortuneClicker;
  window.startMemoryGame = startMemoryGame;
  window.buttonRoulette = buttonRoulette;
  window.hidePixel = hidePixel;
  window.badPassword = badPassword;
  window.addFish = addFish;
  window.feedFish = feedFish;
  window.aquariumEvent = aquariumEvent;
  window.randomSecret = randomSecret;
  window.unlockSecret = unlockSecret;
  window.secretRitual = secretRitual;
  window.makeNoiseText = makeNoiseText;
  window.randomWebringJump = randomWebringJump;
  window.randomObjectShrine = randomObjectShrine;
  window.tvStatic = tvStatic;
  window.voidMessage = voidMessage;
  window.mazeChoice = mazeChoice;
  window.scrambleMeters = scrambleMeters;
  window.generateWarning = generateWarning;
  window.toggleContainment = toggleContainment;
  window.recalibrateBeacon = recalibrateBeacon;
  window.flipPanel = flipPanel;
  window.renderInventory = renderInventory;
  window.renderAchievements = renderAchievements;
  window.showFakeFolder = showFakeFolder;
  window.openFakeFile = openFakeFile;
  window.cursedSearch = cursedSearch;
  window.generateLostPage = generateLostPage;
  window.askArchiveBot = askArchiveBot;
  window.tuneRadio = tuneRadio;
  window.radioPlay = radioPlay;
  window.radioPause = radioPause;
  window.radioStop = radioStop;
  window.setRadioVolume = setRadioVolume;
  window.refreshWeather = refreshWeather;
  window.installFakeUpdate = installFakeUpdate;
  window.viewPatchNotes = viewPatchNotes;
  window.rollbackFakeUpdate = rollbackFakeUpdate;
  window.buyShopItem = buyShopItem;
  window.summonSpiritEntry = summonSpiritEntry;
});
